### ISSUE TITLE
X-ray errors

### ISSUE THREAD

**Issue by goxjia** [xxyzz/WordDumb#10]
`calibre, version 5.23.0 (win32, embedded-python: True)
Eh!: 失败: Generating X-Ray for 三体全集

Starting job: Generating X-Ray for 三体全集 
Job: "Generating X-Ray for 三体全集" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 83, in start_work
  File "calibre_plugins.worddumb.parse_job", line 46, in do_job
  File "calibre_plugins.worddumb.parse_job", line 144, in find_named_entity
  File "calibre_plugins.worddumb.x_ray", line 192, in search
  File "calibre_plugins.worddumb.x_ray", line 149, in insert_entity
  File "calibre_plugins.worddumb.x_ray", line 166, in insert_description
  File "calibre_plugins.worddumb.x_ray", line 95, in search_wikipedia
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\sessions.py", line 555, in get
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\sessions.py", line 542, in request
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\sessions.py", line 655, in send
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\adapters.py", line 439, in send
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\connectionpool.py", line 696, in urlopen
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\connection.py", line 359, in connect
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\connection.py", line 500, in _connect_tls_proxy
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 997, in _create
ValueError: check_hostname requires server_hostname
 
Called with args: ((214, 'KFX', 'C:\\Users\\goxji\\Calibre 书库\\Liu Ci Xin\\San Ti Quan Ji (214)\\San Ti Quan Ji - Liu Ci Xin.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x000002002360E0D0>, {'spacy': 'zh_core_web_', 'wiki': 'zh'}), False, True) {'notifications': <queue.Queue object at 0x000002002371E6A0>, 'abort': <threading.Event object at 0x000002002371EDC0>, 'log': <calibre.utils.logging.GUILog object at 0x000002002371EC10>} 
`

**Comment by xxyzz** [comment]
Something wrong with your proxy configuration. Are you using HTTP proxy? Please read https://2.python-requests.org/en/master/user/advanced/#proxies and check your environment variables.

**Comment by xxyzz** [comment]
If you're using sock5 proxy, you have to install the optional requests dependency [pysocks](https://github.com/Anorov/PySocks) with this command:

```
$ py -m pip install pysocks -t C:\Users\goxji\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8
```
