### ISSUE TITLE
Failing to create x ray for all the books

### ISSUE THREAD

**Issue by himalay-chauhan** [xxyzz/WordDumb#103]
### Checkboxes

- [X] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

Gives the error message as mentioned in error message section while creating x ray for any books

### System Information

OS: Mac 13.2 (22D49)
Calibre version: 6.11.0
Python version: 3.11.0
Plugin version: 3.28.2

### Error message

```text
calibre, version 6.11.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for War of Lanka 
Job: "Generating Word Wise and X-Ray for War of Lanka" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 167, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 59, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/Users/himalaychauhan/Library/Preferences/calibre/plugins/WordDumb.zip', 'BBTXUOB8J5', '/Users/himalaychauhan/Calibre Library/Amish Tripathi/War of Lanka (187)/War of Lanka - Amish Tripathi.azw3', 'War_of_Lanka', 'dd604ce7', 'en_core_web_lg', 'en', 'en', 'utf-8', 'WordDumb/3.28.2 (https://github.com/xxyzz/WordDumb)', 'cn', '', 'AZW3', '1', '/Users/himalaychauhan/Library/Preferences/calibre/plugins/WordDumb.zip', '', '-l', '-x', '-s']' returned non-zero exit status 1.
 
Called with args: ((187, 'AZW3', '/Users/himalaychauhan/Calibre Library/Amish Tripathi/War of Lanka (187)/War of Lanka - Amish Tripathi.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x2aba3bfa0>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x2aba38340>, 'abort': <threading.Event object at 0x2aba39a80>, 'log': <calibre.utils.logging.GUILog object at 0x2aba38220>} 
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/himalaychauhan/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/himalaychauhan/Library/Preferences/calibre/plugins/WordDumb.zip/dump_kindle_lemmas.py", line 13, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

### Reproduce steps

Select any book.
Click on WordDumb and select create x ray

**Comment by xxyzz** [comment]
Please use Homebrew to install Python. You're using Python 3.9 from Apple's command line tools, which is not supported.

**Comment by himalay-chauhan** [comment]
Thank you for quick response. I will try and update here.

Warm Regards,
Himalay Chauhan
________________________________

**Comment by himalay-chauhan** [comment]
> Please use Homebrew to install Python. You're using Python 3.9 from Apple's command line tools, which is not supported.

Thank you. It worked!
