### ISSUE TITLE
Cannot Generate Xray as it shows this error

### ISSUE THREAD

**Issue by mohan-raaj** [xxyzz/WordDumb#109]
I tried to install Xray but it always shows this error. 

Starting job: Generating Word Wise and X-Ray for The Girl With the Dragon Tattoo 
Job: "Generating Word Wise and X-Ray for The Girl With the Dragon Tattoo" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 151, in do_job
  File "calibre_plugins.worddumb.deps", line 49, in install_deps
  File "calibre_plugins.worddumb.deps", line 135, in pip_install
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\USER\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.11', '--no-user', 'https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.5.0/en_core_web_trf-3.5.0-py3-none-any.whl']' returned non-zero exit status 1.
 
Called with args: ((36, 'MOBI', 'C:\\Users\\USER\\Calibre Library\\Stieg Larsson\\The Girl With the Dragon Tattoo (36)\\The Girl With the Dragon Tattoo - Stieg Larsson.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000017DAD3C4C40>, 'en'), True, True) {'notifications': <queue.Queue object at 0x0000017DAD3C4DF0>, 'abort': <threading.Event object at 0x0000017DAD3C4EB0>, 'log': <calibre.utils.logging.GUILog object at 0x0000017DAD3C4DC0>} 
ERROR: Cannot install en-core-web-trf because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by xxyzz** [comment]
Uninstall Python 3.11 then install Python 3.10, PyTorch currently doesn't support Python 3.11 on Windows: https://xxyzz.github.io/WordDumb/installation.html#install-python-3-10-and-pip

**Comment by mohan-raaj** [comment]
Hey! I did as you said now it comes up with this error. Sorry for being dumb.

calibre, version 6.12.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for The Girl With the Dragon Tattoo 
Job: "Generating Word Wise and X-Ray for The Girl With the Dragon Tattoo" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 186, in do_job
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\USER\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "BBNVJWFUQN", "book_path": "C:\\\\Users\\\\USER\\\\Calibre Library\\\\Stieg Larsson\\\\The Girl With the Dragon Tattoo (36)\\\\The Girl With the Dragon Tattoo - Stieg Larsson.mobi", "acr": "The_Girl_with_the_Dragon_Tattoo", "revision": "12d7b62c", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "utf-8", "useragent": "WordDumb/3.29.0 (https://github.com/xxyzz/WordDumb)", "book_fmt": "MOBI", "plugin_path": "C:\\\\Users\\\\USER\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip"}', '{"use_pos": true, "search_people": true, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "https://www.fandom.com/", "add_locator_map": true, "preferred_formats": ["MOBI", "KFX", "AZW3", "AZW", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 5, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu117", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((36, 'MOBI', 'C:\\Users\\USER\\Calibre Library\\Stieg Larsson\\The Girl With the Dragon Tattoo (36)\\The Girl With the Dragon Tattoo - Stieg Larsson.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000019CC168A770>, 'en'), True, True) {'notifications': <queue.Queue object at 0x0000019CC168A890>, 'abort': <threading.Event object at 0x0000019CC168A860>, 'log': <calibre.utils.logging.GUILog object at 0x0000019CC168AAA0>} 
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 40, in <module>
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 353, in create_files
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\x_ray.py", line 193, in finish
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\mediawiki.py", line 477, in query_mediawiki
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\mediawiki.py", line 298, in query
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xxyzz** [comment]
Looks like Wikipedia API returns an empty data, I'm not sure what causes this. Can you still get this error with another book? Please also upload the book file, I'll try to reproduce the error.

**Comment by mohan-raaj** [comment]
I tried it with another book which posted an error below. I tried uploading the book file but github didn't allow me to upload a MOBI file. Again sorry for any inconvenience caused.

calibre, version 6.12.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for 101 Essays That Will Change the Way You Think 
Job: "Generating Word Wise and X-Ray for 101 Essays That Will Change the Way You Think" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 186, in do_job
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\USER\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "BB40IUGTN5", "book_path": "C:\\\\Users\\\\USER\\\\Calibre Library\\\\Brianna Wiest\\\\101 Essays That Will Change the Way (33)\\\\101 Essays That Will Change the - Brianna Wiest.mobi", "acr": "101_Essays_That_Will_Change_the", "revision": "31690757", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "utf-8", "useragent": "WordDumb/3.29.0 (https://github.com/xxyzz/WordDumb)", "book_fmt": "MOBI", "plugin_path": "C:\\\\Users\\\\USER\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip"}', '{"use_pos": true, "search_people": true, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "https://www.fandom.com/", "add_locator_map": true, "preferred_formats": ["MOBI", "KFX", "AZW3", "AZW", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 5, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu117", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((33, 'MOBI', 'C:\\Users\\USER\\Calibre Library\\Brianna Wiest\\101 Essays That Will Change the Way (33)\\101 Essays That Will Change the - Brianna Wiest.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000019CC4FAE020>, 'en'), True, True) {'notifications': <queue.Queue object at 0x0000019CC4FAE0E0>, 'abort': <threading.Event object at 0x0000019CC4FADEA0>, 'log': <calibre.utils.logging.GUILog object at 0x0000019CC4FAE2F0>} 
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 40, in <module>
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 353, in create_files
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\x_ray.py", line 193, in finish
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\mediawiki.py", line 477, in query_mediawiki
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\mediawiki.py", line 298, in query
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xxyzz** [comment]
That means the HTTP response code from Wikipedia API is not 200. I never get this error myself so I can only guess what causes it. Maybe your IP address is banned by Wikipedia or their servers are quite busy at that time. You can try again later to see whether Wikipedia API is available.

I have pushed [two](https://github.com/xxyzz/WordDumb/commit/e8412832a592a02dcd567a36fe0f38750d0d8be4) [commits](https://github.com/xxyzz/WordDumb/commit/b19bd0a539ff9b882abc7e85775690a7eb67e8e0) to ignore these errors. You can download the test plugin in [GitHub Actions Artifacts](https://github.com/xxyzz/WordDumb/actions/runs/4354429809).

**Comment by mohan-raaj** [comment]
Follow up on the issue:-
I could use Wikipedia's data to generate Xray.
However, I could not use data from Fandom and I have attached the error it shows below.

Starting job: Generating Word Wise and X-Ray for A Game of Thrones 
Job: "Generating Word Wise and X-Ray for A Game of Thrones" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 186, in do_job
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\USER\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "BBQLG3OFOU", "book_path": "E:\\\\Calibre\\\\George R. R. Martin\\\\A Game of Thrones (4)\\\\A Game of Thrones - George R. R. Martin.mobi", "acr": "A_Game_of_Thrones", "revision": "92d5398c", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "utf-8", "useragent": "WordDumb/3.29.0 (https://github.com/xxyzz/WordDumb)", "book_fmt": "MOBI", "plugin_path": "C:\\\\Users\\\\USER\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip"}', '{"use_pos": true, "search_people": true, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "https://iceandfire.fandom.com/", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu117", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((4, 'MOBI', 'E:\\Calibre\\George R. R. Martin\\A Game of Thrones (4)\\A Game of Thrones - George R. R. Martin.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000021423EE74C0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x0000021423EE7E80>, 'abort': <threading.Event object at 0x0000021423EE7E20>, 'log': <calibre.utils.logging.GUILog object at 0x0000021423EE76D0>} 
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 40, in <module>
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 353, in create_files
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\x_ray.py", line 220, in finish
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\x_ray.py", line 86, in insert_descriptions
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\WordDumb.zip\mediawiki.py", line 271, in get_cache
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 19 supplied.

**Comment by xxyzz** [comment]
I now know what causes of the `requests.exceptions.JSONDecodeError` error: you input the wrong Fandom URL, www.fandom.com don't have MediaWiki API.

For `sqlite3.ProgrammingError`,  please upload the `C:\Users\USER\AppData\Roaming\calibre\plugins\worddumb-fandom\iceandfire.fandom.com.db` file. Compress the db file in a zip file to upload it.
