### ISSUE TITLE
Word dumb generation error in Mac M1

### ISSUE THREAD

**Issue by BOOMBOOMBIRD** [xxyzz/WordDumb#117]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

使用生词提示出现问题

### System Information

os：macos 13.3.1 (22E261)
Python Version：3.11.3
Calibre Version: 6.15.1
WordDumb version：3.29.1

### Error message

```text
calibre, version 6.15.1 (darwin, embedded-python: True)
We want... a shrubbery!: Please read the friendly manual of how to install Python.

Starting job: 正在為《On Weaving》生成生詞提示和X-Ray 
Job: "正在為《On Weaving》生成生詞提示和X-Ray" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 152, in do_job
    install_deps("lxml", notifications)
  File "calibre_plugins.worddumb.deps", line 36, in install_deps
    PY_PATH, py_version = which_python()
  File "calibre_plugins.worddumb.deps", line 81, in which_python
    r = run_subprocess(
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/bin/python3'
 
Called with args: ((23, 'AZW3', '/Users/l/calibre 書庫/Anni Albers/On Weaving (23)/On Weaving - Anni Albers.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x15ff468c0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x15ff45210>, 'abort': <threading.Event object at 0x15ff46b00>, 'log': <calibre.utils.logging.GUILog object at 0x15ff45ae0>}
```

### Reproduce steps

1.打开calibre
2.选择书籍
3.点击worddumb

**Comment by xxyzz** [comment]
Similar to https://github.com/xxyzz/WordDumb/issues/113. How did you install Python? Have you read the doc: https://xxyzz.github.io/WordDumb/installation.html#install-python-3-10-and-pip as the error message suggested?
