### ISSUE TITLE
Can't Generate Word Wise

### ISSUE THREAD

**Issue by ttttt258** [xxyzz/WordDumb#121]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

calibre, version 6.17.0 (win32, embedded-python: True)
Tonnerre de Brest!: 发生了一个错误，请复制错误信息并到 GitHub 提交错误报告。

Starting job: 正在为《Olive Kitteridge》生成生词提示 
Job: "正在为《Olive Kitteridge》生成生词提示" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 138, in do_job
  File "calibre_plugins.worddumb.deps", line 173, in download_word_wise_file
  File "calibre_plugins.worddumb.deps", line 177, in download_and_extract
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1352, in do_open
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
 
Called with args: ((2, 'AZW3', 'C:\\Users\\22623\\Calibre 书库\\Elizabeth Strout\\Olive Kitteridge (2)\\Olive Kitteridge - Elizabeth Strout.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000230ECB4EB30>, 'en'), True, False) {'notifications': <queue.Queue object at 0x00000230ECB4EC50>, 'abort': <threading.Event object at 0x00000230ECB4EB00>, 'log': <calibre.utils.logging.GUILog object at 0x00000230ECB4EE60>}

### System Information

OS: Windows11 64
calibre : 6.17
worddumb: 3.29
Python version: 3.10

### Error message

```text
can't generate word wise
```

### Reproduce steps

1.go to calibre
2. link with kindle
3. press Worddumb 

### Screenshots or videos

![Uploading IMG_20230429_152341.jpg…]()
![Uploading IMG_20230429_152417.jpg…]()

**Comment by xxyzz** [comment]
That's a network error, please check your network connection.
