### ISSUE TITLE
Error when generating WordWise

### ISSUE THREAD

**Issue by mizake-mizan** [xxyzz/WordDumb#128]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

Following error displayed (fairly early in the process) when attempting to generate WordWise for a document.  This is a machine on which it formerly worked; I don't believe I have made any recent changes other than regular Calibre and Plugin updates.

### System Information

Windows 11
Calibre 6.17
WordDumb 3.29.1
CUDA 11.7

### Error message

```text
calibre, version 6.17.0
ERROR: Unhandled exception: <b>UnicodeDecodeError</b>:'utf-8' codec can't decode byte 0x8e in position 1790: invalid start byte

calibre 6.17  embedded-python: True
Windows-10-10.0.22624-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22624')
Python 3.10.1
Windows: ('10', '10.0.22624', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && Count Pages (1, 13, 0) && Ebook Translator (1, 3, 8) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && Set KFX metadata (from KFX Output) (1, 67, 0) && KFX Output (1, 67, 0) && Modify ePub (1, 8, 1) && Obok DeDRM (10, 0, 3) && WordDumb (3, 29, 1)
Traceback (most recent call last):
  File "calibre\gui2\__init__.py", line 720, in dispatch
  File "calibre_plugins.worddumb.ui", line 144, in done
  File "calibre_plugins.worddumb.error_dialogs", line 43, in job_failed
  File "calibre_plugins.worddumb.error_dialogs", line 71, in subprocess_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1790: invalid start byte
```

### Reproduce steps

1. Select book
2. Choose "Create Word Wise"

**Comment by mizake-mizan** [comment]
Of course, reporting a problem is the best way for it to solve itself :)

If anyone sees anything similar, just delete the **worddumb-libs-py3.10** folder and let it automatically regenerate.
