### ISSUE TITLE
X-Ray not working because link to spacy model is invalid

### ISSUE THREAD

**Issue by plamengj** [xxyzz/WordDumb#138]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

X-Ray not working because link to download the spacy model is invalid.

### System Information

OS: Windows

### Error message

```text
Traceback (most recent call last):   File "calibre\gui2\threaded_jobs.py", line 82, in start_work   File "calibre_plugins.worddumb.parse_job", line 155, in do_job   File "calibre_plugins.worddumb.deps", line 51, in install_deps   File "calibre_plugins.worddumb.deps", line 143, in pip_install   File "calibre_plugins.worddumb.utils", line 56, in run_subprocess   File "subprocess.py", line 524, in run subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\plame\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12', '--no-user', 'https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.0/en_core_web_trf-3.6.0-py3-none-any.whl']' returned non-zero exit status 1.   Called with args: ((142, 'KFX', 'E:\\Calibre Library\\Harry Frankfurt\\On bullshit (142)\\On bullshit - Harry Frankfurt.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000244A9A313C0>, 'en'), False, True) {'notifications': <queue.Queue object at 0x00000244A9A31000>, 'abort': <threading.Event object at 0x00000244A9A31390>, 'log': <calibre.utils.logging.GUILog object at 0x00000244A9A316C0>}   

ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.0/en_core_web_trf-3.6.0-py3-none-any.whl ERROR: Could not install requirement en-core-web-trf==3.6.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.0/en_core_web_trf-3.6.0-py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.0/en_core_web_trf-3.6.0-py3-none-any.whl for URL https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.6.0/en_core_web_trf-3.6.0-py3-none-any.whl
```

### Reproduce steps

 I am guessing this is where the issue is coming from: https://github.com/xxyzz/WordDumb/blob/master/deps.py

**Comment by xxyzz** [comment]
Thanks for your report, v3.29.5 fixes this error.
