### ISSUE TITLE
failed with error

### ISSUE THREAD

**Issue by Ivy76** [xxyzz/WordDumb#140]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

Starting job: 正在為《The Housemaid's Secret》生成生詞提示和X-Ray 
Job: "正在為《The Housemaid's Secret》生成生詞提示和X-Ray" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 37, in install_deps
  File "calibre_plugins.worddumb.deps", line 91, in which_python
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((193, 'EPUB', "C:\\Users\\73771\\calibre 書庫\\Freida McFadden\\The Housemaid's Secret (193)\\The Housemaid's Secret - Freida McFadden.epub", <calibre.ebooks.metadata.book.base.Metadata object at 0x000001BE76EE65F0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001BE76EE6260>, 'abort': <threading.Event object at 0x000001BE76EE6650>, 'log': <calibre.utils.logging.GUILog object at 0x000001BE76EE6380>} 
Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90P

### System Information

calibre 6.23

### Error message

```text
Starting job: 正在為《The Housemaid's Secret》生成生詞提示和X-Ray 
Job: "正在為《The Housemaid's Secret》生成生詞提示和X-Ray" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 37, in install_deps
  File "calibre_plugins.worddumb.deps", line 91, in which_python
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((193, 'EPUB', "C:\\Users\\73771\\calibre 書庫\\Freida McFadden\\The Housemaid's Secret (193)\\The Housemaid's Secret - Freida McFadden.epub", <calibre.ebooks.metadata.book.base.Metadata object at 0x000001BE76EE65F0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001BE76EE6260>, 'abort': <threading.Event object at 0x000001BE76EE6650>, 'log': <calibre.utils.logging.GUILog object at 0x000001BE76EE6380>} 
Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90P
```

### Reproduce steps

Starting job: 正在為《The Housemaid's Secret》生成生詞提示和X-Ray 
Job: "正在為《The Housemaid's Secret》生成生詞提示和X-Ray" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 154, in do_job
  File "calibre_plugins.worddumb.deps", line 37, in install_deps
  File "calibre_plugins.worddumb.deps", line 91, in which_python
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 9009.
 
Called with args: ((193, 'EPUB', "C:\\Users\\73771\\calibre 書庫\\Freida McFadden\\The Housemaid's Secret (193)\\The Housemaid's Secret - Freida McFadden.epub", <calibre.ebooks.metadata.book.base.Metadata object at 0x000001BE76EE65F0>, 'en'), True, True) {'notifications': <queue.Queue object at 0x000001BE76EE6260>, 'abort': <threading.Event object at 0x000001BE76EE6650>, 'log': <calibre.utils.logging.GUILog object at 0x000001BE76EE6380>} 
Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90P

**Comment by xxyzz** [comment]
You need to install Python, please read https://xxyzz.github.io/WordDumb/installation.html
