### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by MINHGUYN** [xxyzz/WordDumb#143]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

I cannot use WordDumb for creating wordwise

### System Information

OS: Win 11
Python: 3.11
Calibre: 6.24
Worddumd: v3.29.5

### Error message

```text
calibre, version 6.13.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for 12 Rules for Life: An Antidote to Chaos 
Job: "Generating Word Wise and X-Ray for 12 Rules for Life: An Antidote to Chaos" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 190, in do_job
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\vanph\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "B078C6C7QS", "book_path": "C:\\\\Users\\\\vanph\\\\Calibre Library\\\\Jordan B. Peterson\\\\12 Rules for Life_ An Antidote to Ch (21)\\\\12 Rules for Life_ An Antidote - Jordan B. Peterson.azw3", "acr": "CR!FBTA06J1FX5BZ1EM2XDXF7E4TVXT", "revision": "d5963d97", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "utf-8", "useragent": "WordDumb/3.29.5 (https://github.com/xxyzz/WordDumb)", "book_fmt": "AZW3", "plugin_path": "C:\\\\Users\\\\vanph\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip"}', '{"use_pos": true, "search_people": false, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu118", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((21, 'AZW3', 'C:\\Users\\vanph\\Calibre Library\\Jordan B. Peterson\\12 Rules for Life_ An Antidote to Ch (21)\\12 Rules for Life_ An Antidote - Jordan B. Peterson.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000028369DDA320>, 'en'), True, True) {'notifications': <queue.Queue object at 0x0000028369DDA860>, 'abort': <threading.Event object at 0x0000028369DDA410>, 'log': <calibre.utils.logging.GUILog object at 0x0000028369DDAD70>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 40, in <module>
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 244, in create_files
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 740, in load_spacy
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\worddumb-libs-py3.11\spacy\__init__.py", line 16, in <module>
    from .cli.info import info  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\worddumb-libs-py3.11\spacy\cli\__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\worddumb-libs-py3.11\spacy\cli\_util.py", line 21, in <module>
    import typer
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\worddumb-libs-py3.11\typer\__init__.py", line 30, in <module>
    from .main import Typer as Typer
  File "C:\Users\vanph\AppData\Roaming\calibre\plugins\worddumb-libs-py3.11\typer\main.py", line 44, in <module>
    console_stderr = Console(stderr=True)
                     ^^^^^^^^^^^^^^^^^^^^
TypeError: Console.__init__() got an unexpected keyword argument 'stderr'
```

### Reproduce steps

It does not work.

**Comment by xxyzz** [comment]
You must have the `rich` package installed somewhere. This is an error in the `typer` package, you could try to uninstall `rich`.

**Comment by MINHGUYN** [comment]
> You must have a strange `rich` package or a very old [`rich`](https://github.com/Textualize/rich) package installed somewhere. You could try to find it and uninstall `rich`.

It works. Many thanks
