### ISSUE TITLE
Unable to Generate WordDumb files

### ISSUE THREAD

**Issue by Cassius-PC** [xxyzz/WordDumb#151]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

Unable to Generate WordDumb files, error produced...

### System Information

OS: Windows 10 Pro
Python:  3.10
Calibre: 6.27

### Error message

```text
calibre, version 6.27.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Happy Sexy Millionaire: Unexpected Truths About Fulfillment, Love, and Success 
Job: "Generating Word Wise and X-Ray for Happy Sexy Millionaire: Unexpected Truths About Fulfillment, Love, and Success" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 203, in do_job
  File "calibre_plugins.worddumb.utils", line 55, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\Cassius\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 311, "book_path": "M:\\\\Cassius\\\\Documents\\\\Calibre Library\\\\Steven Bartlett\\\\Happy Sexy Millionaire_ Unexpected (311)\\\\Happy Sexy Millionaire_ Unexpec - Steven Bartlett.azw3", "mi": null, "book_fmt": "AZW3", "book_lang": "en", "useragent": "WordDumb/3.29.6 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\Cassius\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_trf", "create_ww": true, "create_x": true, "asin": "BB2FAPIQ8H", "acr": "Happy_Sexy_Millionaire__Unexpec", "revision": "373ca9c9", "update_asin": true, "kfx_json": null, "mobi_html": null, "mobi_codec": "utf-8"}', '{"use_pos": true, "search_people": true, "model_size": "sm", "zh_wiki_variant": "cn", "fandom": "https://www.fandom.com", "add_locator_map": false, "preferred_formats": ["AZW3", "KFX", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": true, "cuda": "cu117", "last_opened_kindle_lemmas_language": "en", "last_opened_wiktionary_lemmas_language": "en", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=311, book_path='M:\\Cassius\\Documents\\Calibre Library\\Steven Bartlett\\Happy Sexy Millionaire_ Unexpected (311)\\Happy Sexy Millionaire_ Unexpec - Steven Bartlett.azw3', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x00000251011A8AC0>, book_fmt='AZW3', book_lang='en', useragent='WordDumb/3.29.6 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\Cassius\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_trf', create_ww=True, create_x=True, asin='BB2FAPIQ8H', acr='Happy_Sexy_Millionaire__Unexpec', revision='373ca9c9', update_asin=True, kfx_json=None, mobi_html=None, mobi_codec='utf-8'),) {'notifications': <queue.Queue object at 0x0000025100A50DF0>, 'abort': <threading.Event object at 0x0000025100A51660>, 'log': <calibre.utils.logging.GUILog object at 0x0000025100A51A80>} 
Traceback (most recent call last):
  File "C:\Users\Cassius\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cassius\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cassius\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 39, in <module>
  File "C:\Users\Cassius\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 229, in create_files
  File "C:\Users\Cassius\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 782, in load_spacy
  File "C:\Users\Cassius\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\util.py", line 230, in require_gpu
    raise ValueError("Cannot use GPU, CuPy is not installed")
ValueError: Cannot use GPU, CuPy is not installed
```

### Reproduce steps

USB connection to kindle device

**Comment by xxyzz** [comment]
Somehow spaCy's `thinc` package can't import `cupy` package, you could delete the `C:\Users\Cassius\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10` folder and try again or disable the "use GPU" feature.

**Comment by Cassius-PC** [comment]
Thank you for your assistance. I will try that now

**Comment by Cassius-PC** [comment]
I removed the feature as you suggested. I was able to perform a word wise test, and it was successful. 
I will now try making an x-ray file or test. I will provide my findings.

**Comment by Cassius-PC** [comment]
I have tested both features and they worked. Thank you most profoundly for your assistance!
