### ISSUE TITLE
I got this error message while creating x ray (HELP)

### ISSUE THREAD

**Issue by jackstewert** [xxyzz/WordDumb#22]
calibre, version 5.37.0 (darwin, embedded-python: True)
Mille millions de mille milliards de mille sabords!: subprocess.run() failed, please copy error message then report bug at GitHub

Starting job: Generating X-Ray for Napoleon the Great 
Job: "Generating X-Ray for Napoleon the Great" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 58, in do_job
    subprocess.run(
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip', 'BBPNNLKU26', '/Users/moinqureshi/Calibre Library/Andrew Roberts/Napoleon the Great (39)/Napoleon the Great - Andrew Roberts.kfx', 'CR!SXGJ70N16NVGGGN1XQJDOBYOZLPU', '', 'en_core_web_md', 'en', '', '/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip', '3.18.4', 'cn', '', '-s']' returned non-zero exit status 1.
 
Called with args: ((39, 'KFX', '/Users/moinqureshi/Calibre Library/Andrew Roberts/Napoleon the Great (39)/Napoleon the Great - Andrew Roberts.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x133f93f40>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x133f93550>, 'abort': <threading.Event object at 0x134053820>, 'log': <calibre.utils.logging.GUILog object at 0x1340530a0>} 
Traceback (most recent call last):
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 37, in <module>
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/parse_job.py", line 105, in create_files
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/parse_job.py", line 187, in find_named_entity
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/x_ray.py", line 168, in search
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/x_ray.py", line 133, in insert_entity
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/x_ray.py", line 148, in insert_description
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/WordDumb.zip/x_ray.py", line 85, in search_wikipedia
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/moinqureshi/Library/Preferences/calibre/plugins/worddumb-libs-py3.8/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by xxyzz** [comment]
The error says you can't connect to Wikipedia. Please check your network.

**Comment by jackstewert** [comment]
ok thank you it worked
