### ISSUE TITLE
error on everything

### ISSUE THREAD

**Issue by nonuscolling1** [xxyzz/WordDumb#226]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

calibre, version 7.12.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Saving customized lemmas 
Job: "Saving customized lemmas" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.config", line 377, in dump_lemmas_job
  File "calibre_plugins.worddumb.utils", line 53, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\nonus\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"is_kindle": true, "db_path": "C:\\\\Users\\\\nonus\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\worddumb-lemmas\\\\en\\\\kindle_en_en_v0.db", "lemma_lang": "en", "plugin_path": "C:\\\\Users\\\\nonus\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "model_name": "en_core_web_lg"}', '{"use_pos": true, "search_people": false, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["MOBI", "KFX", "EPUB", "AZW3", "AZW"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": false, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu121", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5, "fandom": "", "last_opened_kindle_lemmas_language": "en", "last_opened_wiktionary_lemmas_language": "en"}']' returned non-zero exit status 1.
 
Called with args: (True, WindowsPath('C:/Users/nonus/AppData/Roaming/calibre/plugins/worddumb-lemmas/en/kindle_en_en_v0.db'), 'en') {'notifications': <queue.Queue object at 0x0000012F6C0E1CD0>, 'abort': <threading.Event at 0x12f6c082990: unset>, 'log': <calibre.utils.logging.GUILog object at 0x0000012F6C119C50>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 22, in <module>
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\WordDumb.zip\dump_lemmas.py", line 59, in dump_spacy_docs
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipeline\attributeruler.py", line 8, in <module>
    from ..language import Language
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\language.py", line 43, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\tokens\__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\tokens\_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "spacy\tokens\doc.pyx", line 49, in init spacy.tokens.doc
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\schemas.py", line 195, in <module>
    class TokenPatternString(BaseModel):
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 529, in update_field_forward_refs
    update_field_forward_refs(sub_f, globalns=globalns, localns=localns)
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### Plugin settings and reproduce steps

calibre, version 7.12.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Saving customized lemmas 
Job: "Saving customized lemmas" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.config", line 377, in dump_lemmas_job
  File "calibre_plugins.worddumb.utils", line 53, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\nonus\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"is_kindle": true, "db_path": "C:\\\\Users\\\\nonus\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\worddumb-lemmas\\\\en\\\\kindle_en_en_v0.db", "lemma_lang": "en", "plugin_path": "C:\\\\Users\\\\nonus\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "model_name": "en_core_web_lg"}', '{"use_pos": true, "search_people": false, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["MOBI", "KFX", "EPUB", "AZW3", "AZW"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": false, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu121", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5, "fandom": "", "last_opened_kindle_lemmas_language": "en", "last_opened_wiktionary_lemmas_language": "en"}']' returned non-zero exit status 1.
 
Called with args: (True, WindowsPath('C:/Users/nonus/AppData/Roaming/calibre/plugins/worddumb-lemmas/en/kindle_en_en_v0.db'), 'en') {'notifications': <queue.Queue object at 0x0000012F6C0E1CD0>, 'abort': <threading.Event at 0x12f6c082990: unset>, 'log': <calibre.utils.logging.GUILog object at 0x0000012F6C119C50>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 22, in <module>
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\WordDumb.zip\dump_lemmas.py", line 59, in dump_spacy_docs
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipeline\attributeruler.py", line 8, in <module>
    from ..language import Language
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\language.py", line 43, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\tokens\__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\tokens\_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "spacy\tokens\doc.pyx", line 49, in init spacy.tokens.doc
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\schemas.py", line 195, in <module>
    class TokenPatternString(BaseModel):
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 529, in update_field_forward_refs
    update_field_forward_refs(sub_f, globalns=globalns, localns=localns)
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\pydantic\v1\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

**Comment by xxyzz** [comment]
The code in error message is mostly spacy and pydantic code, please try the latest test version in GitHub Actions or delete the "C:\Users\nonus\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12" folder.

**Comment by nonuscolling1** [comment]
It does not work. I have deleted everything. Re-installed everything, still the same problem

**Comment by xxyzz** [comment]
What's the pydantic and pydantic-core version in the "worddumb-libs-py3.12" folder? This error should be fixed by the latest pydantic release.
