### ISSUE TITLE
nvcc fatal error

### ISSUE THREAD

**Issue by wylker** [xxyzz/WordDumb#230]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

NVCC throws an error when compiling. This appears to be a problem with the version of CUDA installed but I've double checked already.

Starting job: Generating Word Wise and X-Ray for The Way of Kings 
Job: "Generating Word Wise and X-Ray for The Way of Kings" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 211, in do_job
  File "calibre_plugins.worddumb.utils", line 53, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 5, "book_path": "C:\\\\Users\\\\xxxxx\\\\Calibre Library\\\\Brandon Sanderson\\\\The Way of Kings (5)\\\\The Way of Kings - Brandon Sanderson.kfx", "mi": null, "book_fmt": "KFX", "book_lang": "en", "useragent": "WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\xxxxx\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_trf", "create_ww": true, "create_x": true, "asin": "BB4QHDLYJF", "acr": "CR!UOSBFLNQM6ZJWAAFR8C6YVERHLPZ", "revision": "", "kfx_json": null, "mobi_html": null, "mobi_codec": ""}', '{"use_pos": true, "search_people": true, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": true, "cuda": "cu121", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=5, book_path='C:\\Users\\xxxxx\\Calibre Library\\Brandon Sanderson\\The Way of Kings (5)\\The Way of Kings - Brandon Sanderson.kfx', mi=, book_fmt='KFX', book_lang='en', useragent='WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_trf', create_ww=True, create_x=True, asin='BB4QHDLYJF', acr='CR!UOSBFLNQM6ZJWAAFR8C6YVERHLPZ', revision='', kfx_json=None, mobi_html=None, mobi_codec=''),) {'notifications': , 'abort': , 'log': } 

### Plugin settings and reproduce steps

Windows 10.0.1945
plugin version 3.32.0
Ryzen 7 3800X
CUDA 12.1

![image](https://github.com/xxyzz/WordDumb/assets/2914323/9dcca699-ec0d-4734-ac63-2d3828747e32)

Error occurs when selecting book (book is in KFX format) and selecting "Create Word-Wise and X-Ray" from plugin menu.

### Generated files, screenshots or videos

calibre, version 7.12.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for The Way of Kings 
Job: "Generating Word Wise and X-Ray for The Way of Kings" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 211, in do_job
  File "calibre_plugins.worddumb.utils", line 53, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 5, "book_path": "C:\\\\Users\\\\xxxxx\\\\Calibre Library\\\\Brandon Sanderson\\\\The Way of Kings (5)\\\\The Way of Kings - Brandon Sanderson.kfx", "mi": null, "book_fmt": "KFX", "book_lang": "en", "useragent": "WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\xxxxx\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_trf", "create_ww": true, "create_x": true, "asin": "BB4QHDLYJF", "acr": "CR!UOSBFLNQM6ZJWAAFR8C6YVERHLPZ", "revision": "", "kfx_json": null, "mobi_html": null, "mobi_codec": ""}', '{"use_pos": true, "search_people": true, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": true, "cuda": "cu121", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=5, book_path='C:\\Users\\xxxxx\\Calibre Library\\Brandon Sanderson\\The Way of Kings (5)\\The Way of Kings - Brandon Sanderson.kfx', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x000002A7CFAD22D0>, book_fmt='KFX', book_lang='en', useragent='WordDumb/3.32.0 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_trf', create_ww=True, create_x=True, asin='BB4QHDLYJF', acr='CR!UOSBFLNQM6ZJWAAFR8C6YVERHLPZ', revision='', kfx_json=None, mobi_html=None, mobi_codec=''),) {'notifications': <queue.Queue object at 0x000002A7CFAC8C10>, 'abort': <threading.Event at 0x2a7cfac9b90: unset>, 'log': <calibre.utils.logging.GUILog object at 0x000002A7CFAC99D0>} 
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 64, in _run_cc
    log = subprocess.check_output(cmd, cwd=cwd, env=env,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.1\\bin\\nvcc.EXE', '-gencode=arch=compute_86,code=sm_86', '--ptx', '-DFIRST_PASS=1', '--std=c++11', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\include', '-ftz=true', 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\tmpbwtl7lel\\preprocess.cu']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 366, in compile_using_nvcc
    _run_cc(cmd, root_dir, 'nvcc', log_stream)
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 80, in _run_cc
    raise NVCCException(msg)
cupy.cuda.compiler.NVCCException: `nvcc` command returns non-zero exit status. 
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.1\\bin\\nvcc.EXE', '-gencode=arch=compute_86,code=sm_86', '--ptx', '-DFIRST_PASS=1', '--std=c++11', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\include', '-ftz=true', 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\tmpbwtl7lel\\preprocess.cu']
return-code: 1
stdout/stderr: 
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

tmpxft_000075f0_00000000-2.cpp
nvcc fatal   : Host compiler targets unsupported OS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 37, in <module>
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 253, in create_files
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 828, in create_spacy_matcher
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\WordDumb.zip\dump_lemmas.py", line 110, in save_spacy_docs
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\WordDumb.zip\dump_lemmas.py", line 174, in create_lemma_patterns_with_pos
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\language.py", line 1618, in pipe
    for doc in docs:
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\transition_parser.pyx", line 245, in pipe
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1650, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\pipe.pyx", line 55, in pipe
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\pipe.pyx", line 55, in pipe
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\transition_parser.pyx", line 245, in pipe
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1650, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy\pipeline\trainable_pipe.pyx", line 73, in pipe
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1650, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\util.py", line 1703, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy_curated_transformers\pipeline\transformer.py", line 210, in pipe
    preds = self.predict(batch)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy_curated_transformers\pipeline\transformer.py", line 242, in predict
    return self.model.predict(docs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\model.py", line 334, in predict
    return self._func(self, X, is_train=False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy_curated_transformers\models\architectures.py", line 651, in transformer_model_forward
    Y, backprop_layer = model.layers[0](docs, is_train=is_train)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\model.py", line 310, in __call__
    return self._func(self, X, is_train=is_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy_curated_transformers\models\with_non_ws_tokens.py", line 72, in with_non_ws_tokens_forward
    Y_no_ws, backprop_no_ws = inner(tokens, is_train)
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\model.py", line 310, in __call__
    return self._func(self, X, is_train=is_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\layers\chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\model.py", line 310, in __call__
    return self._func(self, X, is_train=is_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy_curated_transformers\models\with_strided_spans.py", line 103, in with_strided_spans_forward
    doc_len_sums = [int(x.sum()) for x in doc_lens]
                        ^^^^^^^
  File "cupy\_core\core.pyx", line 1090, in cupy._core.core._ndarray_base.sum
  File "cupy\_core\core.pyx", line 1099, in cupy._core.core._ndarray_base.sum
  File "cupy\_core\_routines_math.pyx", line 123, in cupy._core._routines_math._ndarray_sum
  File "cupy\_core\_reduction.pyx", line 608, in cupy._core._reduction._SimpleReductionKernel.__call__
  File "cupy\_core\_reduction.pyx", line 364, in cupy._core._reduction._AbstractReductionKernel._call
  File "cupy\_core\_cub_reduction.pyx", line 701, in cupy._core._cub_reduction._try_to_call_cub_reduction
  File "cupy\_core\_cub_reduction.pyx", line 538, in cupy._core._cub_reduction._launch_cub
  File "cupy\_core\_cub_reduction.pyx", line 473, in cupy._core._cub_reduction._cub_two_pass_launch
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\_cub_reduction.pyx", line 246, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function
  File "cupy\_core\_cub_reduction.pyx", line 231, in cupy._core._cub_reduction._create_cub_reduction_function
  File "cupy\_core\core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 539, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 434, in _preprocess
    result = compile_using_nvcc(source, options, arch, 'preprocess.cu',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 376, in compile_using_nvcc
    raise cex
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status. 
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.1\\bin\\nvcc.EXE', '-gencode=arch=compute_86,code=sm_86', '--ptx', '-DFIRST_PASS=1', '--std=c++11', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\include', '-ftz=true', 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\tmpbwtl7lel\\preprocess.cu']
return-code: 1
stdout/stderr: 
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

tmpxft_000075f0_00000000-2.cpp
nvcc fatal   : Host compiler targets unsupported OS.

**Comment by xxyzz** [comment]
Looks like the compiler is not supported, please check your Visual Studio version: https://docs.nvidia.com/cuda/archive/12.1.1/cuda-installation-guide-microsoft-windows/index.html#system-requirements

**Comment by wylker** [comment]
Hrm. I'm not sure that's the issue. I have MSVC 143 and VS 2022 17.10.x and I've not had a problem compiling otherwise in VS. As far as I know v143 is the latest MVSC compiler, so that 193 is maybe a typo? I thought there may be a command line argument problem when calling the nvcc exe - I've never tried to use it before so I wasn't sure if it was calling for the wrong env? I played with it a bit and got it to move ahead a little but it is still unhappy with my version of VS:

 File "C:\Users\xxxxx\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\cupy\cuda\compiler.py", line 376, in compile_using_nvcc
    raise cex
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status. 
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.1\\bin\\nvcc.EXE', '-gencode=arch=compute_86,code=sm_86', '--ptx', '-DFIRST_PASS=1', '--std=c++11', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include', '-IC:\\Users\\xxxxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.12\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\include', '-ftz=true', 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\tmpgqlrzqao\\preprocess.cu']
return-code: 2
stdout/stderr: 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.

**Comment by xxyzz** [comment]
Please update your compiler to a CUDA supported version. I'm not familiar with CUDA and Windows, I could only suggest you follow the CUDA Installation Guide...

**Comment by xxyzz** [comment]
GPU models are not supported now.
