### ISSUE TITLE
X-Ray not running - Potential python issue - unsure

### ISSUE THREAD

**Issue by dingotoyota** [xxyzz/WordDumb#267]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I'm not sure why x-ray isn't running and continues to get an error message. I've restarted and installed python manually and through windows store. Appreciate any help.

calibre, version 7.20.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for A Little Bit Broken 
Job: "Generating Word Wise and X-Ray for A Little Bit Broken" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 177, in do_job
  File "calibre_plugins.worddumb.deps", line 42, in install_deps
  File "calibre_plugins.worddumb.deps", line 134, in pip_install
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\14166\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.13', '--no-user', '--no-cache-dir', 'spacy==3.8.2']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=25, book_path='C:\\Users\\14166\\Calibre Library\\Roz Weston\\A Little Bit Broken (25)\\A Little Bit Broken - Roz Weston.azw3', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x000002A6BBE91110>, book_fmt='AZW3', book_lang='en', useragent='WordDumb/3.33.1 (https://github.com/xxyzz/WordDumb)', plugin_path=WindowsPath('C:/Users/14166/AppData/Roaming/calibre/plugins/WordDumb.zip'), spacy_model='en_core_web_md', create_ww=True, create_x=True, asin='BBZ1IB0HIB', acr='A_Little_Bit_Broken', revision='bd1b1f4d', kfx_json=None, mobi_html=b'<?xml version="1.0" encoding="UTF-8"?>\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">\n  <head>\n    <title>Continued</title>\n    <meta content="urn:uuid:2586df50-4825-46f8-9e4a-e39ca813bfc5" name="Adept.expected.resource"/>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n  <link rel="stylesheet" type="text/css" href="kindle:flow:0001?mime=text/css"/>\n<link rel="stylesheet" type="text/css" href="kindle:flow:0002?mime=text/css"/>\n</head>\n  <body class="calibre" aid="0">\n\t\t<div id="fm1" class="calibre1" aid="1">\n\t\t\t<div class="figure_nomargin" aid="2">\n\t\t\t\t<span type="pagebreak" id="page_i" role="doc-pagebreak" title="i" class="calibre2" aid="3"></span>\n\t\t\t\t<div class="height_" aid="4">\n\t\t\t\t\t<img alt="" class="fill_height" id="Page_i_img01" src="kindle:embed:0004?mime=image/jpeg" aid="5"/>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</body>\n</html>\n<?xml version="1.0" encoding="UTF-8"?>\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">\n  <head>\n    <title>Title Page</title>\n    <meta content="urn:uuid:2586df50-4825-46f8-9e4a-e39ca813bfc5" name="Adept.expected.resource"/>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n  <link rel="stylesheet" type="text/css" href="kindle:flow:0001?mime=text/css"/>\n<link rel="stylesheet" type="text/css" href="kindle:flow:0002?mime=text/css"/>\n</head>\n  <body type="titlepage" class="calibre" aid="UGI0">\n\t\t<div class="height_" id="tp" aid="UGI1">\n\t\t\t<span type="pagebreak" id="page_ii" role="doc-pagebreak" title="ii" class="calibre2" aid="UGI2"></span>\n\t\t\t<img alt="Book title, A Little Bit Broken: A Memoir, Author, Roz Weston, Imprint, Doubleday Canada" class="fill_height" src="kindle:embed:0005?mime=image/jpeg"/>\n\t\t</div>\n\t</body>\n</html>\n<?xml version="1.0" encoding="UTF-8"?>\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">\n  <head>\n    <title>Copyright</title>\n    <meta content="urn:uuid:2586df50-4825-46f8-9e4a-e39ca813bfc5" [truncated the rest]
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [117 lines of output]
  Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
  Collecting setuptools
    Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
  Collecting cython<3.0,>=0.25
    Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.8.tar.gz (9.8 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting preshed<3.1.0,>=3.0.2
    Using cached preshed-3.0.9.tar.gz (14 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    error: subprocess-exited-with-error
  
    pip subprocess to install build dependencies did not run successfully.
    exit code: 1
  
    [83 lines of output]
    Collecting setuptools
      Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
    Collecting cython>=0.28
      Using cached Cython-3.0.11-cp313-cp313-win_amd64.whl.metadata (3.2 kB)
    Collecting cymem<2.1.0,>=2.0.2
      Using cached cymem-2.0.8.tar.gz (9.8 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting murmurhash<1.1.0,>=0.28.0
      Using cached murmurhash-1.0.10.tar.gz (12 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Using cached setuptools-75.2.0-py3-none-any.whl (1.2 MB)
    Using cached Cython-3.0.11-cp313-cp313-win_amd64.whl (2.8 MB)
    Building wheels for collected packages: cymem, murmurhash
      Building wheel for cymem (pyproject.toml): started
      Building wheel for cymem (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error
  
      Building wheel for cymem (pyproject.toml) did not run successfully.
      exit code: 1
  
      [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\cymem
      copying cymem\about.py -> build\lib.win-amd64-cpython-313\cymem
      copying cymem\__init__.py -> build\lib.win-amd64-cpython-313\cymem
      creating build\lib.win-amd64-cpython-313\cymem\tests
      copying cymem\tests\test_import.py -> build\lib.win-amd64-cpython-313\cymem\tests
      copying cymem\tests\__init__.py -> build\lib.win-amd64-cpython-313\cymem\tests
      copying cymem\cymem.pyx -> build\lib.win-amd64-cpython-313\cymem
      copying cymem\cymem.pxd -> build\lib.win-amd64-cpython-313\cymem
      copying cymem\__init__.pxd -> build\lib.win-amd64-cpython-313\cymem
      running build_ext
      building 'cymem.cymem' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for cymem
      Building wheel for murmurhash (pyproject.toml): started
      Building wheel for murmurhash (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error
  
      Building wheel for murmurhash (pyproject.toml) did not run successfully.
      exit code: 1
  
      [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\murmurhash
      copying murmurhash\about.py -> build\lib.win-amd64-cpython-313\murmurhash
      copying murmurhash\__init__.py -> build\lib.win-amd64-cpython-313\murmurhash
      creating build\lib.win-amd64-cpython-313\murmurhash\tests
      copying murmurhash\tests\test_hash.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
      copying murmurhash\tests\test_import.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
      copying murmurhash\tests\__init__.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
      copying murmurhash\mrmr.pyx -> build\lib.win-amd64-cpython-313\murmurhash
      copying murmurhash\mrmr.pxd -> build\lib.win-amd64-cpython-313\murmurhash
      copying murmurhash\__init__.pxd -> build\lib.win-amd64-cpython-313\murmurhash
      creating build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
      running build_ext
      building 'murmurhash.mrmr' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for murmurhash
    Failed to build cymem murmurhash
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cymem, murmurhash)
    [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Plugin settings and reproduce steps

1) Install word dumb
2) Run on AZW3 book file
3) Error message above 

### Generated files, screenshots or videos

![Screenshot 2024-10-18 212740](https://github.com/user-attachments/assets/38a514fc-8162-4cb1-b2a1-e0d9802179cd)

**Comment by dingotoyota** [comment]
I've also tried deleting .json and the worddumb-libs-pyX.XX folders with no change

**Comment by MikadoH** [comment]
I have the same issue (same version of calibre, only mine is for mac, also tried it with AZW3 files).

**Comment by ak-988** [comment]
Same issue with KFX here.

**Comment by ak-988** [comment]
> I had the same issue. What is your current Python version? Mine was 13, but I uninstalled it and reinstalled version 12. Now it works smoothly. I think it only works with Python 12.

Good call! Downgrading from 3.13 to 3.12 (Windows x64) solved it for me.

**Comment by xxyzz** [comment]
Some dependency packages haven't release pre-build wheel files for Python 3.13, please use 3.12 or install a compiler as the error message says.
