### ISSUE TITLE
Have been trying to make Worddumb to work for 6 hours :(

### ISSUE THREAD

**Issue by Snickth** [xxyzz/WordDumb#270]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

I clean installed my windows.
Installed python
installed calibre 
installed worddumb plugin
everytime I try to run worddumb plugin it starts downloading in the job process and then I get this error message.

calibre, version 7.20.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Keep Going 
Job: "Generating Word Wise and X-Ray for Keep Going" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 177, in do_job
  File "calibre_plugins.worddumb.deps", line 42, in install_deps
  File "calibre_plugins.worddumb.deps", line 134, in pip_install
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\xxx\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.13', '--no-user', '--no-cache-dir', 'spacy==3.8.2']' returned non-zero exit status 1.
 
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [113 lines of output]
      Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting cython<3.0,>=0.25
        Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.8.tar.gz (9.8 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting preshed<3.1.0,>=3.0.2
        Using cached preshed-3.0.9.tar.gz (14 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [81 lines of output]
            Collecting setuptools
              Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
            Collecting cython>=0.28
              Using cached Cython-3.0.11-cp313-cp313-win_amd64.whl.metadata (3.2 kB)
            Collecting cymem<2.1.0,>=2.0.2
              Using cached cymem-2.0.8.tar.gz (9.8 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting murmurhash<1.1.0,>=0.28.0
              Using cached murmurhash-1.0.10.tar.gz (12 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
            Using cached Cython-3.0.11-cp313-cp313-win_amd64.whl (2.8 MB)
            Building wheels for collected packages: cymem, murmurhash
              Building wheel for cymem (pyproject.toml): started
              Building wheel for cymem (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error
      
              × Building wheel for cymem (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [15 lines of output]
                  running bdist_wheel
                  running build
                  running build_py
                  creating build\lib.win-amd64-cpython-313\cymem
                  copying cymem\about.py -> build\lib.win-amd64-cpython-313\cymem
                  copying cymem\__init__.py -> build\lib.win-amd64-cpython-313\cymem
                  creating build\lib.win-amd64-cpython-313\cymem\tests
                  copying cymem\tests\test_import.py -> build\lib.win-amd64-cpython-313\cymem\tests
                  copying cymem\tests\__init__.py -> build\lib.win-amd64-cpython-313\cymem\tests
                  copying cymem\cymem.pyx -> build\lib.win-amd64-cpython-313\cymem
                  copying cymem\cymem.pxd -> build\lib.win-amd64-cpython-313\cymem
                  copying cymem\__init__.pxd -> build\lib.win-amd64-cpython-313\cymem
                  running build_ext
                  building 'cymem.cymem' extension
                  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for cymem
              Building wheel for murmurhash (pyproject.toml): started
              Building wheel for murmurhash (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error
      
              × Building wheel for murmurhash (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [19 lines of output]
                  running bdist_wheel
                  running build
                  running build_py
                  creating build\lib.win-amd64-cpython-313\murmurhash
                  copying murmurhash\about.py -> build\lib.win-amd64-cpython-313\murmurhash
                  copying murmurhash\__init__.py -> build\lib.win-amd64-cpython-313\murmurhash
                  creating build\lib.win-amd64-cpython-313\murmurhash\tests
                  copying murmurhash\tests\test_hash.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
                  copying murmurhash\tests\test_import.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
                  copying murmurhash\tests\__init__.py -> build\lib.win-amd64-cpython-313\murmurhash\tests
                  copying murmurhash\mrmr.pyx -> build\lib.win-amd64-cpython-313\murmurhash
                  copying murmurhash\mrmr.pxd -> build\lib.win-amd64-cpython-313\murmurhash
                  copying murmurhash\__init__.pxd -> build\lib.win-amd64-cpython-313\murmurhash
                  creating build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
                  copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
                  copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win-amd64-cpython-313\murmurhash\include\murmurhash
                  running build_ext
                  building 'murmurhash.mrmr' extension
                  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for murmurhash
            Failed to build cymem murmurhash
            ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cymem, murmurhash)
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Plugin settings and reproduce steps

default setting plugin

**Comment by xxyzz** [comment]
Same as #267, downgrade to Python 3.12 or install "Microsoft C++ Build Tools".
