### ISSUE TITLE
Error when creating X-Ray

### ISSUE THREAD

**Issue by KeePach** [xxyzz/WordDumb#276]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

when creating X-ray, it stops and the following error occurs:

`calibre, version 7.21.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating X-Ray for The Assassin of Grins and Secrets 
Job: "Generating X-Ray for The Assassin of Grins and Secrets" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 210, in do_job
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['py', 'C:\\Users\\jhmp_\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 448, "book_path": "G:\\\\bibliobooks\\\\K. E. Andrews\\\\The Assassin of Grins and Secrets (448)\\\\The Assassin of Grins and Secre - K. E. Andrews_x_ray.epub", "mi": null, "book_fmt": "EPUB", "book_lang": "en", "useragent": "WordDumb/3.33.1 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\jhmp_\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_lg", "create_ww": false, "create_x": true, "asin": "", "acr": "", "revision": "", "kfx_json": null, "mobi_html": null, "mobi_codec": ""}', '{"search_people": false, "model_size": "lg", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": true, "preferred_formats": ["EPUB", "KFX", "AZW3", "AZW", "MOBI"], "use_all_formats": false, "minimal_x_ray_count": 3, "choose_format_manually": false, "gloss_lang": "en", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hi_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "id_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "ms_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "nb_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5, "cuda": "cu121", "fandom": "", "kindle_gloss_lang": "en", "use_gpu": false, "use_pos": true, "wiktionary_gloss_lang": "en"}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=448, book_path='G:\\bibliobooks\\K. E. Andrews\\The Assassin of Grins and Secrets (448)\\The Assassin of Grins and Secre - K. E. Andrews_x_ray.epub', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x000002458E7ED290>, book_fmt='EPUB', book_lang='en', useragent='WordDumb/3.33.1 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\jhmp_\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_lg', create_ww=False, create_x=True, asin='', acr='', revision='', kfx_json=None, mobi_html=None, mobi_codec=''),) {'notifications': <queue.Queue object at 0x0000024592D3E690>, 'abort': <threading.Event at 0x24592d1e010: unset>, 'log': <calibre.utils.logging.GUILog object at 0x0000024592D1C210>} 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\WordDumb.zip\__main__.py", line 37, in <module>
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 236, in create_files
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\WordDumb.zip\parse_job.py", line 724, in load_spacy
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\types.py", line 25, in <module>
    from .compat import cupy, has_cupy
  File "C:\Users\jhmp_\AppData\Roaming\calibre\plugins\worddumb-libs-py3.12\thinc\compat.py", line 35, in <module>
    import torch
  File "C:\Users\jhmp_\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] No se puede encontrar el m\xf3dulo especificado. Error loading "C:\Users\jhmp_\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
`

### Plugin settings and reproduce steps

1. connect the device
2. select the book
3. click "create X-ray"
4. error occurs

**Comment by xxyzz** [comment]
Please download and test the plugin from here https://github.com/xxyzz/WordDumb/actions/runs/11984678379

**Comment by xxyzz** [comment]
You have the pytorch package installed in ""C:\Users\jhmp_\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch", seems like a user install path? If the "-I" option can't prevent Python to find the pytorch package in this path then you have to uninstall the package.

**Comment by KeePach** [comment]
manually deleting the folder solved the issue although, I don't know why it was being called if the plugin doesn't make use of it.

**Comment by xxyzz** [comment]
The dependency package "thinc" has some code try to import pytorch, it's in the error log.
