### ISSUE TITLE
How to fix this ???

### ISSUE THREAD

**Issue by Mikukub** [xxyzz/WordDumb#28]
### Describe the bug

I can not use word wise

### System Information

OS: [e.g. Windows 10, 64bit]
calibre version: [e.g. 5.24.0, 64bit]
Python version: [e.g. 3.9.6, 64bit]
Plugin version [e.g. 3.10.4]

### Error message

```shell
calibre, version 5.40.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub. 

Starting job: Generating X-Ray for [Title here] 
Job: "Generating X-Ray for [Title here]" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 63, in do_job
  File "calibre_plugins.worddumb.deps", line 23, in __init__
  File "calibre_plugins.worddumb.deps", line 65, in install_x_ray_deps
  File "calibre_plugins.worddumb.deps", line 75, in pip_install
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', 'install', '-U', '-t', WindowsPath('C:/Users/Kaoru/AppData/Roaming/calibre/plugins/worddumb-libs-py3.8'), '--no-deps', 'https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.2.0/en_core_web_lg-3.2.0-py3-none-any.whl']' returned non-zero exit status 2.
 
Called with args: ((67, 'EPUB', 'C:\\Users\\Kaoru\\Calibre Library\\Mishima Yomu volume 3\\[Title here] (67)\\[Title here] - Mishima Yomu volume 3.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000267E6784CD0>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x00000267E6784F70>, 'abort': <threading.Event object at 0x00000267E67849D0>, 'log': <calibre.utils.logging.GUILog object at 0x00000267E6784910>} 
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 305, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 195, in prepare_linked_requirement
    unpack_url(
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 1058, in unpack_url
    unpack_http_url(
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 920, in unpack_http_url
    from_path, content_type = _download_http_url(link,
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 863, in _download_url
    consume(downloaded_chunks)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\utils\misc.py", line 1056, in consume
    deque(iterator, maxlen=0)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 829, in written_chunks
    for chunk in chunks:
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_internal\download.py", line 794, in resp_read
    for chunk in resp.raw.stream(
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 479, in read
    data = self._fp.read(amt)
  File "C:\Users\Kaoru\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 63, in read
    self.__buf.write(data)
MemoryError
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

### Reproduce steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

**Comment by xxyzz** [comment]
spaCy large model is about 700MB and your computer runs out of memory when pip reads that file. Please use smaller spaCy model or update Python and pip.

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/0d083238ff5d739d655ce84b03cba3724c685eef should fix this error. But you will probably still have MemoryError when spaCy starts loading the large model.
