### ISSUE TITLE
Outdated pyhton on M1 macOS

### ISSUE THREAD

**Issue by kasogiak92** [xxyzz/WordDumb#280]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

i'm using 
Calibre 7.22
WordDumb 3.33
Pyhton 3.12

but then it said "Your Phyton version is too old"

Starting job: Generating Word Wise and X-Ray for The Poppy War 
Job: "Generating Word Wise and X-Ray for The Poppy War" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 176, in do_job
    install_deps("lxml", notifications)
  File "calibre_plugins.worddumb.deps", line 30, in install_deps
    PY_PATH, py_version = which_python()
                          ^^^^^^^^^^^^^^
  File "calibre_plugins.worddumb.deps", line 91, in which_python
    raise Exception("OutdatedPython")
Exception: OutdatedPython

### Plugin settings and reproduce steps

-

### Generated files, screenshots or videos

![image](https://github.com/user-attachments/assets/80f9a904-7520-4458-b506-61ced50b302f)

**Comment by xxyzz** [comment]
Please check your installed Python version. macos users should install Python 3.12 from Homebrew then copy the Python binary path to the plugin settings.

**Comment by andraskadar** [comment]
I have faced similar issues. First it failed for me and it seamed that it was using Python 3.13 (installed via brew). After uninstalling Python 3.13, I faced the exact same issue. My theory is that in some ways it falls back to the system default version, which in my case was 3.8.9 (`/usr/bin/python3 --version`).

After explicitly setting the Python path as mentioned above, the issue was solved:
<img width="530" alt="Image" src="https://github.com/user-attachments/assets/5d154bdc-6d57-44bf-809f-5a28ba913cf1" />
