### ISSUE TITLE
Error while creating X-Ray

### ISSUE THREAD

**Issue by ammargitham** [xxyzz/WordDumb#283]
### Checkboxes

- [X] I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
- [X] I have not found similar open/closed issue or disscussion.
- [X] Reboot doesn't fix the problem.

### Describe the bug and copy the error message

The job fails with the following error:

```
calibre, version 7.22.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for The Way of Kings 
Job: "Generating Word Wise and X-Ray for The Way of Kings" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 85, in start_work
  File "calibre_plugins.worddumb.parse_job", line 210, in do_job
  File "calibre_plugins.worddumb.utils", line 47, in run_subprocess
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['C:/Users/Ammar Githam/.pyenv/pyenv-win/shims/python.bat', 'C:\\Users\\Ammar Githam\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', '{"book_id": 23, "book_path": "D:\\\\Calibre\\\\Brandon Sanderson\\\\The Way of Kings (23)\\\\The Way of Kings - Brandon Sanderson.azw3", "mi": null, "book_fmt": "AZW3", "book_lang": "en", "useragent": "WordDumb/3.33.1 (https://github.com/xxyzz/WordDumb)", "plugin_path": "C:\\\\Users\\\\Ammar Githam\\\\AppData\\\\Roaming\\\\calibre\\\\plugins\\\\WordDumb.zip", "spacy_model": "en_core_web_md", "create_ww": true, "create_x": true, "asin": "BBN4WYE32F", "acr": "The_Way_of_Kings", "revision": "e348e4c7", "kfx_json": null, "mobi_html": null, "mobi_codec": "utf-8"}', '{"search_people": false, "model_size": "md", "zh_wiki_variant": "cn", "mediawiki_api": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "choose_format_manually": true, "gloss_lang": "en", "use_wiktionary_for_kindle": false, "remove_link_styles": false, "python_path": "C:/Users/Ammar Githam/.pyenv/pyenv-win/shims/python.bat", "show_change_kindle_ww_lang_warning": true, "ca_wiktionary_difficulty_limit": 5, "cs_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "he_wiktionary_difficulty_limit": 5, "hi_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "id_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "ms_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "nb_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 255.
 
Called with args: (ParseJobData(book_id=23, book_path='D:\\Calibre\\Brandon Sanderson\\The Way of Kings (23)\\The Way of Kings - Brandon Sanderson.azw3', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x0000025D4DC38950>, book_fmt='AZW3', book_lang='en', useragent='WordDumb/3.33.1 (https://github.com/xxyzz/WordDumb)', plugin_path='C:\\Users\\Ammar Githam\\AppData\\Roaming\\calibre\\plugins\\WordDumb.zip', spacy_model='en_core_web_md', create_ww=True, create_x=True, asin='BBN4WYE32F', acr='The_Way_of_Kings', revision='e348e4c7', kfx_json=None, mobi_html=None, mobi_codec='utf-8'),) {'notifications': <queue.Queue object at 0x0000025D4DC076D0>, 'abort': <threading.Event at 0x25d4dc3d590: unset>, 'log': <calibre.utils.logging.GUILog object at 0x0000025D4DC3D710>} 
\\The was unexpected at this time.

```

### Plugin settings and reproduce steps

No special settings change, except that I had to set the python_path in the config since I use pyenv.

**Comment by xxyzz** [comment]
The log doesn't say much what's the error, maybe it's something wrong with your pyenv configuration?

Isn't the ".bat" file supposed to run in shell? The Python path should be an executable file, like ".exe" on Windows.
