### ISSUE TITLE
How to fix this please?

### ISSUE THREAD

**Issue by Mamuko500** [xxyzz/WordDumb#30]
### Describe the bug

It just don't work.

### System Information

Python Version: 3.9 (64-bit)
Plugin version: 3.19.0

### Error message

```text
calibre, version 5.41.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub. 

Starting job: Generating Word Wise and X-Ray for Good Rich People 
Job: "Generating Word Wise and X-Ray for Good Rich People" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 101, in do_job
  File "calibre_plugins.worddumb.parse_job", line 169, in create_files
  File "C:\Users\tibor\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\spacy\__init__.py", line 11, in <module>
  File "C:\Users\tibor\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\thinc\api.py", line 2, in <module>
  File "C:\Users\tibor\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\thinc\initializers.py", line 4, in <module>
  File "C:\Users\tibor\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\thinc\backends\__init__.py", line 8, in <module>
  File "C:\Users\tibor\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\thinc\backends\cupy_ops.py", line 19, in <module>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
  File "thinc\backends\linalg.pyx", line 2, in init thinc.backends.linalg
ValueError: source code string cannot contain null bytes
 
Called with args: ((733, 'KFX', 'C:\\Users\\tibor\\Calibre Library\\Eliza Jane Brazier\\Good Rich People (733)\\Good Rich People - Eliza Jane Brazier.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001F5B40BB1F0>, {'spacy': 'en_core_web_', 'wiki': 'en'}), True, True) {'notifications': <queue.Queue object at 0x000001F5B40BB340>, 'abort': <threading.Event object at 0x000001F5B40BB460>, 'log': <calibre.utils.logging.GUILog object at 0x000001F5B40BB5B0>}
```

### Reproduce steps

It does not work. HELP PLESE

**Comment by xxyzz** [comment]
Maybe the thinc package is corrupted, please delete folder `~/AppData/Roaming/calibre/plugins/worddumb-libs-py3.8` and try again.
