### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by carlofajardo** [xxyzz/WordDumb#33]
### Describe the bug

Create X-Ray suddenly stopped working.

Two error messages is attached.

### System Information

OS: macOS Big Sur 11.6, Mac mini M1 2020
calibre 5.43.0
WordDumb 3.21.0

### Error message

```text
// Error 1
calibre, version 5.43.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating X-Ray for Deep Work 
Job: "Generating X-Ray for Deep Work" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 68, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 25, in install_deps
    PY_PATH, PY_VERSION = which_python()
  File "calibre_plugins.worddumb.deps", line 47, in which_python
    py = mac_python(True)
  File "calibre_plugins.worddumb.deps", line 64, in mac_python
    upgrade_mac_pip()
  File "calibre_plugins.worddumb.deps", line 126, in upgrade_mac_pip
    r = run_subprocess([PY_PATH, "-m", "pip", "--version"])
NameError: name 'PY_PATH' is not defined
 
Called with args: ((81, 'EPUB', '/Users/carlo/Calibre Library/Cal Newport/Deep Work (81)/Deep Work - Cal Newport.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x13bb20e20>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x13bb20c70>, 'abort': <threading.Event object at 0x13b9d44c0>, 'log': <calibre.utils.logging.GUILog object at 0x13b9d48b0>} 

// Error 2
calibre, version 5.43.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating X-Ray for Can't Hurt Me: Master Your Mind and Defy the Odds 
Job: "Generating X-Ray for Can't Hurt Me: Master Your Mind and Defy the Odds" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 68, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 25, in install_deps
    PY_PATH, PY_VERSION = which_python()
  File "calibre_plugins.worddumb.deps", line 47, in which_python
    py = mac_python(True)
  File "calibre_plugins.worddumb.deps", line 64, in mac_python
    upgrade_mac_pip()
  File "calibre_plugins.worddumb.deps", line 126, in upgrade_mac_pip
    r = run_subprocess([PY_PATH, "-m", "pip", "--version"])
NameError: name 'PY_PATH' is not defined
 
Called with args: ((82, 'EPUB', "/Users/carlo/Calibre Library/David Goggins/Can't Hurt Me_ Master Your Mind and Defy the Odds (82)/Can't Hurt Me_ Master Your Mind and Defy t - David Goggins.epub", <calibre.ebooks.metadata.book.base.Metadata object at 0x13ba49cd0>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x13ba49eb0>, 'abort': <threading.Event object at 0x13be9f190>, 'log': <calibre.utils.logging.GUILog object at 0x13be9f2e0>}
```

### Reproduce steps

1. Click dropdown icon of WordDumb
2. Click 'Create X-ray'
3. Error

**Comment by xxyzz** [comment]
Thanks for your report, https://github.com/xxyzz/WordDumb/commit/621d94f9a5d38cb210bf6c0988b28d2b4e975649 should fix this error, you can download the test version from GitHub Action: https://github.com/xxyzz/WordDumb/actions/runs/2427140146

**Comment by carlofajardo** [comment]
I can confirm that the issue no longer happens with the test version. Thank you!
