### ISSUE TITLE
How can I fix this error

### ISSUE THREAD

**Issue by haochiang** [xxyzz/WordDumb#36]
### Describe the bug

when I run the wordDumb ,I got an error like below.

### System Information

OS：windows 11 64bit
Calibre version：5.43 64bit
python version：I installed anaconda（64bit）instead of directly install python
plugin version：3.21.2

### Error message

```text
calibre, version 5.43.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Great Expectations (远大前程) (免费公版书) 
Job: "Generating Word Wise and X-Ray for Great Expectations (远大前程) (免费公版书)" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 68, in do_job
  File "calibre_plugins.worddumb.deps", line 25, in install_deps
  File "calibre_plugins.worddumb.deps", line 43, in which_python
  File "calibre_plugins.worddumb.utils", line 37, in run_subprocess
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['python', '-c', 'import sys; print(sys.maxsize > 2**32)']' returned non-zero exit status 9009.
 
Called with args: ((63, 'AZW3', 'F:\\EBooks\\Calibre Library\\Dickens,Charles\\Great Expectations (Yuan Da Qian Che (63)\\Great Expectations (Yuan Da Qia - Dickens,Charles.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001C70E4B8160>, {'spacy': 'en_core_web_', 'wiki': 'en'}), True, True) {'notifications': <queue.Queue object at 0x000001C70E4B84F0>, 'abort': <threading.Event object at 0x000001C70E4D2C70>, 'log': <calibre.utils.logging.GUILog object at 0x000001C70E4D2E20>}
```

### Reproduce steps

1.run wordDumb 
2.error occurred

### Screenshots or videos

![image](https://user-images.githubusercontent.com/2077295/173274535-458d902d-16c7-4bcc-88f8-0c5813a9a1fc.png)

**Comment by xxyzz** [comment]
What's the output of `python -c "import sys; print(sys.maxsize > 2**32)""`?

You should install python as the README says. IIRC, anaconda uses `conda` not `pip`, so it may fails again later when the program installs packages with `pip`.

**Comment by haochiang** [comment]
> 
thanks，I'll try it later

**Comment by haochiang** [comment]
I fixed this error.It's my fault ,I set the wrong path of Python.
