### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by uumutgun** [xxyzz/WordDumb#39]
calibre, version 5.44.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\LENOVO\\Downloads\\WordDumbmaster.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.44  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 63, 0) && KFX Output (1, 63, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 283, in load
  File "calibre\customize\zipplugin.py", line 378, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\LENOVO\\Downloads\\WordDumbmaster.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by xxyzz** [comment]
Please read the [README file](https://github.com/xxyzz/WordDumb#how-to-use) of how to install the plugin, you also use 32bit calibre which is not supported.

**Comment by uumutgun** [comment]
I am facing this problem. I changed the spaCy setting as you said. I changed my calibre to 64 bit and uploaded python. The problem is not only in this book, this is the only one that I copied the error.

calibre, version 5.44.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Hacking the Universe: The Process of Yogic Meditation 
Job: "Generating Word Wise and X-Ray for Hacking the Universe: The Process of Yogic Meditation" failed with error: 
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\models.py", line 971, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 116, in do_job
  File "calibre_plugins.worddumb.parse_job", line 213, in create_files
  File "calibre_plugins.worddumb.x_ray", line 164, in finish
  File "calibre_plugins.worddumb.mediawiki", line 278, in query_mediawiki
  File "calibre_plugins.worddumb.mediawiki", line 129, in query
  File "C:\Users\LENOVO\AppData\Roaming\calibre\plugins\worddumb-libs-py3.8\requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
Called with args: ((34, 'KFX', 'C:\\Users\\LENOVO\\Desktop\\Calibre BOOKS\\Forrest Knutson\\Hacking the Universe_ The Process of (34)\\Hacking the Universe_ The Proce - Forrest Knutson.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000286D7F33B50>, {'spacy': 'en_core_web_', 'wiki': 'en'}), True, True) {'notifications': <queue.Queue object at 0x00000286D7FB7CA0>, 'abort': <threading.Event object at 0x00000286D7FBF550>, 'log': <calibre.utils.logging.GUILog object at 0x00000286D7FBF640>}

**Comment by xxyzz** [comment]
Maybe your IP or the plugin useragent is blocked by Wikipedia. You could change your IP or try again later.

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/e8412832a592a02dcd567a36fe0f38750d0d8be4 fixes this error.
