### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by ali-oem** [xxyzz/WordDumb#4]
calibre, version 5.18.0 (linux, embedded-python: True)
Dumb error: Failed: Generating Word Wise for Range: Why Generalists Triumph in a Specialized World

Starting job: Generating Word Wise for Range: Why Generalists Triumph in a Specialized World 
Job: "Generating Word Wise for Range: Why Generalists Triumph in a Specialized World" failed with error: 
Traceback (most recent call last):
  File "urllib/request.py", line 1350, in do_open
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "http/client.py", line 1417, in connect
  File "http/client.py", line 921, in connect
  File "socket.py", line 808, in create_connection
  File "socket.py", line 796, in create_connection
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 83, in start_work
  File "calibre_plugins.worddumb.parse_job", line 32, in do_job
    find_named_entity(start, text, x_ray)
  File "calibre_plugins.worddumb.parse_job", line 112, in find_named_entity
    x_ray.search(token, node.label(), token_start, text[index:])
  File "calibre_plugins.worddumb.x_ray", line 134, in search
    self.insert_entity(name, tag, start, text)
  File "calibre_plugins.worddumb.x_ray", line 104, in insert_entity
    self.search_wikipedia()
  File "calibre_plugins.worddumb.x_ray", line 55, in search_wikipedia
    with urllib.request.urlopen(req) as f:
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 1393, in https_open
  File "urllib/request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
 
Called with args: ((64, 'AZW3', 'B07H1ZYWTM', '/home/ali/Calibre Library/David Epstein/Range_ Why Generalists Triumph in a Specialized World (64)/Range_ Why Generalists Triumph in a Specia - David Epstein.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x7f07ec67ffa0>), True) {'notifications': <queue.Queue object at 0x7f07ec67f8e0>, 'abort': <threading.Event object at 0x7f07f1549880>, 'log': <calibre.utils.logging.GUILog object at 0x7f07f1549280>}

**Comment by xxyzz** [comment]
You can't open https://en.wikipedia.org/w/api.php? As the error says, it's a network issue.

**Comment by ali-oem** [comment]
> You can't open https://en.wikipedia.org/w/api.php? As the error says, it's a network issue.

Restarted the PC and it worked again, thank you

**Comment by ali-oem** [comment]
Worked once but now i'm having this:

calibre, version 5.18.0
ERROR: Unhandled exception: <b>OSError</b>:[Errno 30] Read-only file system: '/media/ali/Kindle/documents/Corner, Frances/Why Fashion Matters - Frances Corner.sdr/LanguageLayer.en.BB1A701AOK.kll'

calibre 5.18  embedded-python: True is64bit: True
Linux-5.8.0-53-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-53-generic', '#60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && Package KFX (from KFX Input) (1, 39, 0) && Annotations (1, 15, 0) && Generate Cover (2, 0, 2) && Goodreads (1, 5, 1) && Goodreads More Tags (1, 2, 1) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Set KFX metadata (from KFX Output) (1, 52, 0) && KFX Output (1, 52, 0) && KindleXRay (0, 0, 4) && Prettify Cover (1, 5, 0) && Quality Check (1, 11, 2) && Resize Cover (1, 1, 0) && WordDumb (3, 7, 3) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "shutil.py", line 788, in move
OSError: [Errno 18] Invalid cross-device link: '/home/ali/Calibre Library/Frances Corner/Why Fashion Matters (67)/LanguageLayer.en.BB1A701AOK.kll' -> '/media/ali/Kindle/documents/Corner, Frances/Why Fashion Matters - Frances Corner.sdr/LanguageLayer.en.BB1A701AOK.kll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/__init__.py", line 508, in dispatch
  File "calibre_plugins.worddumb.main", line 69, in done
    sf.send_files(None)
  File "calibre_plugins.worddumb.send_file", line 29, in send_files
    self.move_file_to_device(self.ll_path, device_book_path)
  File "calibre_plugins.worddumb.send_file", line 53, in move_file_to_device
    shutil.move(str(file_path), str(dst_path))
  File "shutil.py", line 802, in move
  File "shutil.py", line 432, in copy2
  File "shutil.py", line 261, in copyfile
OSError: [Errno 30] Read-only file system: '/media/ali/Kindle/documents/Corner, Frances/Why Fashion Matters - Frances Corner.sdr/LanguageLayer.en.BB1A701AOK.kll'

**Comment by xxyzz** [comment]
Your Kindle is mounted as read only, run `sudo fdisk -l` to find the Kindle device then run `sudo fsck` to fix the file system.

**Comment by ali-oem** [comment]
Working after reinstall of Calibre,thanks !

> Your Kindle is mounted as read only, run `sudo fdisk -l` to find the Kindle device then run `sudo fsck` on the device to fix its file system.
