### ISSUE TITLE
There is no item named 'lemmas_dump' in the archive

### ISSUE THREAD

**Issue by Tailslide** [xxyzz/WordDumb#42]
### Describe the bug

When I select my book and click the star I see the error below.
Not sure what to do.

### System Information

Windows 10
Calibre 6.1.0 x64
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32

### Error message

```text
Starting job: Generating Word Wise and X-Ray for Book Name
Job: "Generating Word Wise and X-Ray for Book Name" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 149, in do_job
  File "calibre_plugins.worddumb.parse_job", line 242, in create_files
  File "calibre_plugins.worddumb.utils", line 90, in load_lemmas_dump
  File "calibre_plugins.worddumb.utils", line 33, in load_json_or_pickle
  File "zipfile.py", line 1503, in open
  File "zipfile.py", line 1430, in getinfo
KeyError: "There is no item named 'lemmas_dump' in the archive"
 
Called with args: ((8253, 'KFX', '\\\\nas5\\GregsDocs\\Calibre Library\\Author Name\\Book Name (8253)\\Book Name - Author Name.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000013BE98C29B0>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x0000013BE98C2BF0>, 'abort': <threading.Event object at 0x0000013BE98C2920>, 'log': <calibre.utils.logging.GUILog object at 0x0000013BE98C2A40>}
```

### Reproduce steps

Select book, click on star

**Comment by xxyzz** [comment]
`lemmas_dump` is a generated file, you could download the test plugin from [GitHub Action Artifact](https://github.com/xxyzz/WordDumb/actions/runs/2681641802) or [create the file yourself](https://github.com/xxyzz/WordDumb/blob/master/docs/CONTRIBUTING.md#debug).

**Comment by Tailslide** [comment]
Ahh ok thanks! I grabbed it from the previous release.
