### ISSUE TITLE
Error message while trying to use wordwise

### ISSUE THREAD

**Issue by ezxpro** [xxyzz/WordDumb#44]
### Describe the bug

I tried creating word wise for a book, an error popped up, saying I should report it here. No idea what caused it.

### System Information

Windows 11 x64 21H2
Plugin v3.23.1
Calibre 6.0.1 x64
Python 3.10 x64

### Error message

```text
calibre, version 6.1.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Structure and Interpretation of Computer Programs 
Job: "Generating Word Wise and X-Ray for Structure and Interpretation of Computer Programs" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 149, in do_job
  File "calibre_plugins.worddumb.parse_job", line 246, in create_files
  File "calibre_plugins.worddumb.parse_job", line 570, in load_spacy
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\__init__.py", line 6, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\errors.py", line 2, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\compat.py", line 38, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\api.py", line 2, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\initializers.py", line 4, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\backends\__init__.py", line 8, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\backends\cupy_ops.py", line 4, in <module>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ModuleNotFoundError: No module named 'cymem.cymem'
 
Called with args: ((516, 'EPUB', 'X:\\#Others\\Calibre_Data\\Biblioteca\\Harold Abelson\\Structure and Interpretation of Com (516)\\Structure and Interpretation of - Harold Abelson.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001BE85760220>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x000001BE85762140>, 'abort': <threading.Event object at 0x000001BE833D3130>, 'log': <calibre.utils.logging.GUILog object at 0x000001BE833D1FC0>}
```

### Reproduce steps

1 Select given book
2. Click on worddumb
3. select option to create wordwise plus x ray
4. get the error message

**Comment by xxyzz** [comment]
Looks similar to #41. Please delete the `cymem*` and `thinc*` folders in the `worddumb-libs-py3.10` folder and let the plugin reinstall these packages.

**Comment by ezxpro** [comment]
> Looks similar to #41. Please delete the `cymem*` and `thinc*` folders in the `worddumb-libs-py3.10` folder and let the plugin reinstall these packages.

I did that, now what I see is this:
```
Starting job: Generating Word Wise and X-Ray for Structure and Interpretation of Computer Programs 
Job: "Generating Word Wise and X-Ray for Structure and Interpretation of Computer Programs" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 149, in do_job
  File "calibre_plugins.worddumb.parse_job", line 246, in create_files
  File "calibre_plugins.worddumb.parse_job", line 570, in load_spacy
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\__init__.py", line 6, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\errors.py", line 2, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\spacy\compat.py", line 38, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\api.py", line 2, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\initializers.py", line 4, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\backends\__init__.py", line 8, in <module>
  File "C:\Users\ezbie\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\thinc\backends\cupy_ops.py", line 4, in <module>
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ModuleNotFoundError: No module named 'preshed.maps'
 
Called with args: ((516, 'AZW3', 'X:\\#Others\\Calibre_Data\\Biblioteca\\Harold Abelson\\Structure and Interpretation of Com (516)\\Structure and Interpretation of - Harold Abelson.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001A6FB3469E0>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x000001A6FB346B90>, 'abort': <threading.Event object at 0x000001A6FB346950>, 'log': <calibre.utils.logging.GUILog object at 0x000001A6FB346C20>} 
```

**Comment by xxyzz** [comment]
It seems some packages were not installed correctly. You should delete the `worddumb-libs-py3.10` folder then try again.
