### ISSUE TITLE
Error message while trying to use wordwise

### ISSUE THREAD

**Issue by aliafshany** [xxyzz/WordDumb#45]
### Describe the bug

Error message while trying to use wordwise

### System Information

Mac os 11.6.2
calibre version: 6.1.0
Python version: 3.10.4, 64bit

### Error message

```text
calibre, version 6.1.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise for Influence 
Job: "Generating Word Wise for Influence" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 87, in do_job
    dump_wiktionary_job(plugin_path, lang, True, notifications=notifications)
  File "calibre_plugins.worddumb.parse_job", line 188, in dump_wiktionary_job
    download_and_dump_wiktionary(
  File "calibre_plugins.worddumb.data.wiktionary", line 142, in download_and_dump_wiktionary
    extract_wiktionary(download_path, lang["wiki"], kindle_lemmas, notif)
  File "calibre_plugins.worddumb.data.wiktionary", line 45, in extract_wiktionary
    data = json.loads(line)
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 899 (char 898)
 
Called with args: ((81, 'EPUB', '/Users/afshany/Calibre Library/Robert B. Cialdini, PhD/Influence (81)/Influence - Robert B. Cialdini, PhD.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x1252da4d0>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, False) {'notifications': <queue.Queue object at 0x125278c10>, 'abort': <threading.Event object at 0x125278ac0>, 'log': <calibre.utils.logging.GUILog object at 0x125278a00>}
```

### Reproduce steps

1 Select the given book
2. Click on worddumb
3. select the option to create wordwise
4. get the error message

**Comment by aliafshany** [comment]
it was my issue🤦🏻‍♂️
I didn't convert books to az3w first

**Comment by aliafshany** [comment]
No, it's working great.
But I forgot to convert my books to az3w to make WordDumb work.
now everything is ok
thank you for guiding
