### ISSUE TITLE
Error while running wordwise

### ISSUE THREAD

**Issue by ravimulpuri** [xxyzz/WordDumb#50]
### Describe the bug

Hi,

I get the following error while running wordwise 

Thanks
Ravi

### System Information

OS: MACOS 12.3.1
Calibre: 6.1
Plugin: 3.23.1
Python: 3.7

### Error message

```
Starting job: Generating Word Wise and X-Ray for Buy This, Not That: How to Spend Your Way to Wealth and Freedom 
Job: "Generating Word Wise and X-Ray for Buy This, Not That: How to Spend Your Way to Wealth and Freedom" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 105, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 33, in install_deps
    install_x_ray_deps(model, reinstall, notif)
  File "calibre_plugins.worddumb.deps", line 67, in install_x_ray_deps
    pip_install_pkgs(
  File "calibre_plugins.worddumb.deps", line 106, in pip_install_pkgs
    pip_install(
  File "calibre_plugins.worddumb.deps", line 101, in pip_install
    run_subprocess(args)
  File "calibre_plugins.worddumb.utils", line 48, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-U', '-t', PosixPath('/Users/rtm/Library/Preferences/calibre/plugins/worddumb-libs-py3.7'), '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--python-version', '3.7', 'numpy==1.23.1']' returned non-zero exit status 1.
 
Called with args: ((80, 'AZW3', '/Users/rtm/Calibre Library/Sam Dogen/Buy This, Not That_ How to Spend Your Way to Wealth and Freedom (80)/Buy This, Not That_ How to Spend Your Way - Sam Dogen.azw3', , {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': , 'abort': , 'log': } 
```
```


### Reproduce steps

1. Clicked the book
2. Clicked generated wordwise and X-ray
3. Got error in the job list

**Comment by xxyzz** [comment]
Please also copy error of the subprocess command, it should be at the end of the error message.

I never run the code on Python 3.7, not sure what happened, maybe pip was trying to compile package.

**Comment by ravimulpuri** [comment]
Thanks. I have upgraded to 3.8 and that solved the issue. Is it possible to mention minimum python requirement in the README.md
