### ISSUE TITLE
msvcrt unsurprisingly missing under Linux

### ISSUE THREAD

**Issue by Philantrop** [xxyzz/WordDumb#54]
### Describe the bug

Thanks for the error message but there's no "worddumb-libs-py*" directory (which I expected to find at/below $HOME/.config/calibre/plugins/). 

This is using a fresh installation of the plugin. "python3 -m pip --version --disable-pip-version-check" returns 0 but I expect you're using some other version...

### System Information

OS: Fedora 36, x86_64
calibre version: 6.2.0, 64-bit
Python version: 3.10.5, 64-bit
Plugin version: 3.24.0

### Error message

```text
calibre, version 6.2.0 (linux, embedded-python: True)
Welcome to dependency hell: Please delete the 'msvcrt*' folder from the 'worddumb-libs-py*' folder and try again.

Starting job: Generating X-Ray for Sörensen hat Angst 
Job: "Generating X-Ray for Sörensen hat Angst" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 105, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 22, in install_deps
    PY_PATH, PY_VERSION = which_python()
  File "calibre_plugins.worddumb.deps", line 56, in which_python
    upgrade_pip(py)
  File "calibre_plugins.worddumb.deps", line 127, in upgrade_pip
    r = run_subprocess(
  File "calibre_plugins.worddumb.utils", line 48, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', '--version', '--disable-pip-version-check']' returned non-zero exit status 1.
 
Called with args: ((10440, 'KFX', '/home/krueger/calibre/Sven Stricker/Sorensen hat Angst (10440)/Sorensen hat Angst - Sven Stricker.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x7f6c4f123e20>, {'spacy': 'de_core_news_', 'wiki': 'de', 'kaikki': 'German'}), False, True) {'notifications': <queue.Queue object at 0x7f6c4f122aa0>, 'abort': <threading.Event object at 0x7f6c4f1222f0>, 'log': <calibre.utils.logging.GUILog object at 0x7f6c4f123220>} 
Traceback (most recent call last):
  File "/usr/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 21, in <module>
    from pip._vendor.packaging.utils import canonicalize_name
  File "/usr/lib/python3.10/site-packages/pip/_vendor/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/usr/lib/python3.10/site-packages/pip/_vendor/packaging/tags.py", line 6, in <module>
    import platform
  File "/usr/lib/python3.10/platform.py", line 119, in <module>
    import subprocess
  File "/usr/lib/python3.10/subprocess.py", line 74, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'

```
```


### Reproduce steps

Just trying to generate Xray files is enough

### Screenshots or videos

_No response_

**Comment by xxyzz** [comment]
That delete dependency folder error message is for some weird dependency errors. But this error is even weirder...

That check pip version command runs without error when you run it manually? Did you install calibre via that official `wget | sudo` command or `dnf`?

**Comment by Philantrop** [comment]
Yes, the very same pip call works fine manually. Calibre is installed via the usual wget command as well.
Am 29. Juli 2022, 12:40 +0200 schrieb xxyzz ***@***.***>:

**Comment by Philantrop** [comment]
krueger@kronos ~ $ export PYTHONHOME=/usr/lib64/python3.10  
krueger@kronos ~ $ calibre

```
calibre, version 6.2.1 (linux, embedded-python: True)
Welcome to dependency hell: Please delete the 'encodings*' folder from the 'worddumb-libs-py*' folder and try again.

Starting job: Generating X-Ray for Sörensen hat Angst 
Job: "Generating X-Ray for Sörensen hat Angst" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 105, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 22, in install_deps
    PY_PATH, PY_VERSION = which_python()
  File "calibre_plugins.worddumb.deps", line 56, in which_python
    upgrade_pip(py)
  File "calibre_plugins.worddumb.deps", line 127, in upgrade_pip
    r = run_subprocess(
  File "calibre_plugins.worddumb.utils", line 48, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python3', '-m', 'pip', '--version', '--disable-pip-version-check']' returned non-zero exit status 1.
 
Called with args: ((10440, 'KFX', '/home/krueger/calibre/Sven Stricker/Sorensen hat Angst (10440)/Sorensen hat Angst - Sven Stricker.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x7f4640b7b070>, {'spacy': 'de_core_news_', 'wiki': 'de', 'kaikki': 'German'}), False, True) {'notifications': <queue.Queue object at 0x7f4629fb4190>, 'abort': <threading.Event object at 0x7f4629fb42b0>, 'log': <calibre.utils.logging.GUILog object at 0x7f4629fb4340>} 
Python path configuration:
  PYTHONHOME = '/usr/lib64/python3.10'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr/lib64/python3.10'
  sys.base_exec_prefix = '/usr/lib64/python3.10'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr/lib64/python3.10'
  sys.exec_prefix = '/usr/lib64/python3.10'
  sys.path = [
    '/usr/lib64/python3.10/lib/python310.zip',
    '/usr/lib64/python3.10/lib/python3.10',
    '/usr/lib64/python3.10/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007efecc46d740 (most recent call first):
  <no Python frame>

```

I'm going to try and install the "encodings" module.

**Comment by Philantrop** [comment]
Scratch that, Python really hates life now:

krueger@kronos ~ $ dnf search encodings
```
Python path configuration:
  PYTHONHOME = '/usr/lib64/python3.10'
  PYTHONPATH = (not set)
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr/lib64/python3.10'
  sys.base_exec_prefix = '/usr/lib64/python3.10'
  sys.platlibdir = 'lib64'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr/lib64/python3.10'
  sys.exec_prefix = '/usr/lib64/python3.10'
  sys.path = [
    '/usr/lib64/python3.10/lib64/python310.zip',
    '/usr/lib64/python3.10/lib64/python3.10',
    '/usr/lib64/python3.10/lib64/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ff426b2a740 (most recent call first):
  <no Python frame>

```

**Comment by xxyzz** [comment]
Python can't find it's standard library when run in the calibre subprocess, I have no idea how did that happen.

**Comment by xxyzz** [comment]
When I use the absolute Python path it works, still don't know why.

**Comment by Philantrop** [comment]
Sadly, your fix didn't help. Same error.

**Comment by xxyzz** [comment]
Thanks to Kvoid's help, this commit should fix the error for real.

**Comment by Philantrop** [comment]
Thank you very much! That fixed this issue.
