### ISSUE TITLE
ERROR: No matching distribution found for MarkupSafe==2.1.1

### ISSUE THREAD

**Issue by thetimetraveler** [xxyzz/WordDumb#57]
I am not able to run X-Ray because plugin cannot find the library. 

```
calibre, version 6.2.1 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating X-Ray for Permission to Feel: Unlocking the Power of Emotions to Help Our Kids, Ourselves, and Our Society Thrive 
Job: "Generating X-Ray for Permission to Feel: Unlocking the Power of Emotions to Help Our Kids, Ourselves, and Our Society Thrive" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 105, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 34, in install_deps
    install_x_ray_deps(model, reinstall, notif)
  File "calibre_plugins.worddumb.deps", line 68, in install_x_ray_deps
    pip_install_pkgs(
  File "calibre_plugins.worddumb.deps", line 108, in pip_install_pkgs
    pip_install(
  File "calibre_plugins.worddumb.deps", line 103, in pip_install
    run_subprocess(args)
  File "calibre_plugins.worddumb.utils", line 48, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-U', '-t', PosixPath('/Users/amansingh/Library/Preferences/calibre/plugins/worddumb-libs-py3.8'), '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--no-user', '--python-version', '3.8', 'MarkupSafe==2.1.1']' returned non-zero exit status 1.
 
Called with args: ((9, 'MOBI', '/Users/amansingh/Calibre Library/Marc Brackett, Ph.d_/Permission to Feel_ Unlocking the Power of Emotions to Help Our Kids, Ourselves, and Our Society (9)/Permission to Feel_ Unlocking the Power of - Marc Brackett, Ph.d_.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x137bde980>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), False, True) {'notifications': <queue.Queue object at 0x137bde740>, 'abort': <threading.Event object at 0x137bde7d0>, 'log': <calibre.utils.logging.GUILog object at 0x137bdea10>} 
ERROR: Could not find a version that satisfies the requirement MarkupSafe==2.1.1 (from versions: 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1)
ERROR: No matching distribution found for MarkupSafe==2.1.1
```

**Comment by xxyzz** [comment]
I don't know what went wrong with pip and pypi.org. If you install the latest version of plugin, it upgrades pip and pip should install packages without a issue.

**Comment by xxyzz** [comment]
v3.27.0 probable would fix this error.
