### ISSUE TITLE
Can't  use "customize kindle word wise" function

### ISSUE THREAD

**Issue by yypk** [xxyzz/WordDumb#62]
### Describe the bug

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && Chinese Text Conversion (2, 4, 0) && EpubMerge (2, 14, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && WordDumb (3, 24, 0) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\main.py", line 456, in send_message
  File "calibre\gui2\listener.py", line 91, in send_message_in_process
OSError: Failed to connect to Listener at: \\.\pipe\CalibreGUI-kayuex with error: QLocalSocket::connectToServer: Invalid name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\main.py", line 460, in send_message
  File "calibre\gui2\listener.py", line 91, in send_message_in_process
OSError: Failed to connect to Listener at: \\.\pipe\CalibreGUI-kayuex with error: QLocalSocket::connectToServer: Invalid name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\main.py", line 548, in main
  File "calibre\gui2\main.py", line 561, in run_main
  File "calibre\gui2\main.py", line 494, in communicate
  File "calibre\gui2\main.py", line 465, in send_message
calibre.gui2.main.FailedToCommunicate: retrying

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.worddumb.config", line 187, in open_custom_lemmas_dialog
  File "calibre_plugins.worddumb.custom_lemmas", line 46, in __init__
  File "calibre_plugins.worddumb.custom_lemmas", line 237, in __init__
**TypeErroTypeErrorr: expected str, bytes or os.PathLike object, not NoneType**

### System Information

calibre 6.2.1 ,64bit
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
Python 3.10.1 ,64bit
Worddumb 3.24.0

### Error message

```text
calibre 6.2.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && Chinese Text Conversion (2, 4, 0) && EpubMerge (2, 14, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && WordDumb (3, 24, 0) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\main.py", line 456, in send_message
  File "calibre\gui2\listener.py", line 91, in send_message_in_process
OSError: Failed to connect to Listener at: \\.\pipe\CalibreGUI-kayuex with error: QLocalSocket::connectToServer: Invalid name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\main.py", line 460, in send_message
  File "calibre\gui2\listener.py", line 91, in send_message_in_process
OSError: Failed to connect to Listener at: \\.\pipe\CalibreGUI-kayuex with error: QLocalSocket::connectToServer: Invalid name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\main.py", line 548, in main
  File "calibre\gui2\main.py", line 561, in run_main
  File "calibre\gui2\main.py", line 494, in communicate
  File "calibre\gui2\main.py", line 465, in send_message
calibre.gui2.main.FailedToCommunicate: retrying

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.worddumb.config", line 187, in open_custom_lemmas_dialog
  File "calibre_plugins.worddumb.custom_lemmas", line 46, in __init__
  File "calibre_plugins.worddumb.custom_lemmas", line 237, in __init__
**TypeErroTypeErrorr: expected str, bytes or os.PathLike object, not NoneType**
```

### Reproduce steps

When I click the "customize kindle word wise" button, it pops up an error message 
TypeErroTypeErrorr: expected str, bytes or os.PathLike object, not NoneType

### Screenshots or videos

![擷取](https://user-images.githubusercontent.com/94770095/183273955-a1a150d7-a4f3-4a66-b546-788372163c70.PNG)

**Comment by xxyzz** [comment]
Your device doesn't have the Kindle Word Wise database file `kll.en.en.klld` or `WordWise.kll.en.en.db`. Read a Word Wise enabled book will download this file, you can send a book via the plugin or download one from Amazon.

**Comment by yypk** [comment]
Fixed. Thank you !
But is there any way to add more vocabularies as the words that have explanation are too few.

**Comment by xxyzz** [comment]
Kindle can only display words inside the Word Wise database, add more words is tricky as this requires not only concise definitions but also more data to fill in that database.

Kindle's db has 79134 lemmas that have definitions, that's not a small number...
