### ISSUE TITLE
File not found error on certain books

### ISSUE THREAD

**Issue by Fluff663** [xxyzz/WordDumb#63]
### Describe the bug

When running with certain books it hands off an error

### System Information

OS:Windows 10 Pro
Calibre: 6.3
Python: 3.5.2
Plugin: 3.25.0

### Error message

```text
calibre, version 6.3.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Mistborn: The Final Empire 
Job: "Generating Word Wise and X-Ray for Mistborn: The Final Empire" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 82, in do_job
  File "calibre_plugins.worddumb.deps", line 170, in download_wiktionary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Fluff\\AppData\\Roaming\\calibre\\plugins\\worddumb-lemmas\\wiktionary_en_v0.1.0.tar.gz'
 
Called with args: ((32, 'EPUB', 'C:\\Users\\Fluff\\Calibre Library\\Brandon Sanderson\\Mistborn_ The Final Empire (32)\\Mistborn_ The Final Empire - Brandon Sanderson.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x000002BEB7EE3760>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x000002BEB7EDE6E0>, 'abort': <threading.Event object at 0x000002BEB7EDE7A0>, 'log': <calibre.utils.logging.GUILog object at 0x000002BEB7EDE830>}
```

### Reproduce steps

Select books
Run the plugin

**Comment by xxyzz** [comment]
https://github.com/xxyzz/WordDumb/commit/e5a06268f780e119e4b31c395fabf23f57b3e96b should fix this error.

There is an outage of GitHub Actions, you can install this zip file to test:
[worddumb-e5a06268f780e119e4b31c395fabf23f57b3e96b.zip](https://github.com/xxyzz/WordDumb/files/9428704/worddumb-e5a06268f780e119e4b31c395fabf23f57b3e96b.zip)
