### ISSUE TITLE
SSLEOFError with proxy

### ISSUE THREAD

**Issue by juncheung01** [xxyzz/WordDumb#68]
### Describe the bug

with trojan proxy, and get this error

### System Information

OS: Windows 10 ,x64
calibre version: 6.4.0
plugin version: 3.25.0

### Error message

```text
Starting job: 正在为《阿勒泰的角落》生成X-Ray 
Job: "正在为《阿勒泰的角落》生成X-Ray" failed with error: 
Traceback (most recent call last):
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\connectionpool.py", line 700, in urlopen
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\connectionpool.py", line 996, in _prepare_proxy
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\connection.py", line 364, in connect
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\connection.py", line 499, in _connect_tls_proxy
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\adapters.py", line 489, in send
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\connectionpool.py", line 787, in urlopen
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zh.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?format=json&action=query&prop=extracts%7Cpageprops&exintro=1&explaintext=1&redirects=1&exsentences=7&formatversion=2&ppprop=wikibase_item&variant=zh-cn&titles=%E9%98%BF%E5%8B%92%E6%B3%B0%7C%E5%8C%97%E4%BA%AC%7C%E6%96%B0%E6%98%9F%E5%87%BA%E7%89%88%E7%A4%BE%7C%E4%B8%AD%E5%9B%BD%7C%E4%BB%98%E4%B8%BD%E6%B1%9F%7C%E5%8C%97%E4%BA%AC%E5%B8%82%7C%E8%A5%BF%E5%9F%8E%E5%8C%BA%E8%BD%A6%E5%85%AC%E5%BA%84%E5%A4%A7%E8%A1%97%7C%E5%8C%97%E4%BA%AC%E5%9B%BD%E5%BD%A9%E5%8D%B0%E5%88%B7%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%7C%E9%98%BF%E5%8B%92%E6%B3%B0%E5%9C%B0%E5%A7%94%E5%AE%A3%E4%BC%A0%E9%83%A8%7C%E5%9B%9B%E5%A4%B4%E7%89%9B%7C%E5%9B%9B%E5%B7%9D%7C%E6%B8%B8%E7%89%A7%7C%E9%98%BF%E5%B0%94%E6%B3%B0%7C%E5%93%88%E8%90%A8%E5%85%8B%7C%E9%A2%9D%E5%B0%94%E9%BD%90%E6%96%AF%E6%B2%B3%7C%E5%B7%B4%E6%8B%89%E5%B0%94%E8%8C%A8%7C%E6%B2%99%E4%BE%9D%E6%A8%AA%E5%B8%83%E6%8B%89%E5%85%8B%7C%E6%A1%A5%E5%A4%B4%7C%E6%89%98%E6%B5%B7%7C%E6%88%88%E5%A3%81%E6%BB%A9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 144, in do_job
  File "calibre_plugins.worddumb.parse_job", line 275, in create_files
  File "calibre_plugins.worddumb.x_ray", line 169, in finish
  File "calibre_plugins.worddumb.mediawiki", line 286, in query_mediawiki
  File "calibre_plugins.worddumb.mediawiki", line 134, in query
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\sessions.py", line 600, in get
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\sessions.py", line 587, in request
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\sessions.py", line 701, in send
  File "C:\Users\junch\AppData\Roaming\calibre\plugins\worddumb-libs-py3.10\requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='zh.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?format=json&action=query&prop=extracts%7Cpageprops&exintro=1&explaintext=1&redirects=1&exsentences=7&formatversion=2&ppprop=wikibase_item&variant=zh-cn&titles=%E9%98%BF%E5%8B%92%E6%B3%B0%7C%E5%8C%97%E4%BA%AC%7C%E6%96%B0%E6%98%9F%E5%87%BA%E7%89%88%E7%A4%BE%7C%E4%B8%AD%E5%9B%BD%7C%E4%BB%98%E4%B8%BD%E6%B1%9F%7C%E5%8C%97%E4%BA%AC%E5%B8%82%7C%E8%A5%BF%E5%9F%8E%E5%8C%BA%E8%BD%A6%E5%85%AC%E5%BA%84%E5%A4%A7%E8%A1%97%7C%E5%8C%97%E4%BA%AC%E5%9B%BD%E5%BD%A9%E5%8D%B0%E5%88%B7%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%7C%E9%98%BF%E5%8B%92%E6%B3%B0%E5%9C%B0%E5%A7%94%E5%AE%A3%E4%BC%A0%E9%83%A8%7C%E5%9B%9B%E5%A4%B4%E7%89%9B%7C%E5%9B%9B%E5%B7%9D%7C%E6%B8%B8%E7%89%A7%7C%E9%98%BF%E5%B0%94%E6%B3%B0%7C%E5%93%88%E8%90%A8%E5%85%8B%7C%E9%A2%9D%E5%B0%94%E9%BD%90%E6%96%AF%E6%B2%B3%7C%E5%B7%B4%E6%8B%89%E5%B0%94%E8%8C%A8%7C%E6%B2%99%E4%BE%9D%E6%A8%AA%E5%B8%83%E6%8B%89%E5%85%8B%7C%E6%A1%A5%E5%A4%B4%7C%E6%89%98%E6%B5%B7%7C%E6%88%88%E5%A3%81%E6%BB%A9 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
 
Called with args: ((282, 'KFX', 'C:\\Users\\junch\\Documents\\calibre_lib\\Li Juan\\A Le Tai De Jiao Luo (282)\\A Le Tai De Jiao Luo - Li Juan.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001C670D339D0>, {'spacy': 'zh_core_web_', 'wiki': 'zh', 'kaikki': 'Chinese'}), False, True) {'notifications': <queue.Queue object at 0x000001C689A0B8E0>, 'abort': <threading.Event object at 0x000001C689A0B700>, 'log': <calibre.utils.logging.GUILog object at 0x000001C689A0B9D0>}
```

### Reproduce steps

1.create X-Ray
2.get error

**Comment by xxyzz** [comment]
Please read [calibre FAQ](https://manual.calibre-ebook.com/faq.html#how-do-i-get-calibre-to-use-my-http-proxy) first then check your proxy environment variables, they should be set by these commands:

```
$ export HTTP_PROXY='http://host:port'
$ export HTTPS_PROXY='http://host:port'
```

If you're allergic to terminal, close your proxy and use a VPN.
