### ISSUE TITLE
Wordwise works but X-Ray doesn't

### ISSUE THREAD

**Issue by benninkcorien** [xxyzz/WordDumb#7]
Wordwise seems to run fine, X-Ray errors : 

    Traceback (most recent call last):
    File "calibre\gui2\threaded_jobs.py", line 83, in start_work
    File "calibre_plugins.worddumb.parse_job", line 37, in do_job
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\spacy_3.1.1_3.8\spacy\__init__.py", line 11, in <module>
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\thinc_8.0.8_3.8\thinc\__init__.py", line 5, in <module>
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\thinc_8.0.8_3.8\thinc\config.py", line 14, in <module>
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\srsly_2.4.1_3.8\srsly\__init__.py", line 1, in <module>
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\srsly_2.4.1_3.8\srsly\_json_api.py", line 6, in <module>
    File "C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\srsly_2.4.1_3.8\srsly\ujson\__init__.py", line 1, in <module>
    ModuleNotFoundError: No module named 'srsly.ujson.ujson'

pip says srsly is installed correctly, and C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\srsly_2.4.1_3.8\srsly\ujson
exists and has ujson.c inside among other files.. 

(unrelated? : I had to manually add blis_0.7.4_3.8 to the worddumb-libs on Windows 10 to clear an other error) 

C:\Users\USERNAME\AppData\Roaming\calibre\plugins\worddumb-libs\srsly_2.4.1_3.8\srsly\ujson\__init__.py line 1 is :

from .ujson import decode, encode, dump, dumps, load, loads  # noqa: F401

 Called with args: ((1587, 'MOBI', 'BBGL0Z779A', 'book.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x082C44C0>, {'spacy': 'en_core_web_', 'wiki': 'en'}), False, True) {'notifications': <queue.Queue object at 0x082C46B8>, 'abort': <threading.Event object at 0x082C45F8>, 'log': <calibre.utils.logging.GUILog object at 0x082C45C8>} 

Windows 10
Python 3.9
Calibre - 5.24

Installed the plugin today.

**Comment by xxyzz** [comment]
Both `srsly` and `blis` are compiled package, and both only provide 64bit whl file. Maybe you're using 32bit OS or 32bit caliber and somehow the build process failed while installing these packages. Install 64bit calibre should solve the error.

**Comment by Gamer10222** [comment]
Can you also make it work on 32bit Calibre, so the portable version of Calibre (which is only avaible in 32bit) can be used with your fantastic plugin?

**Comment by xxyzz** [comment]
I don't maintenance these packages , you have to build them by yourself. And you need a compiler, for Windows, download https://visualstudio.microsoft.com/visual-cpp-build-tools. I didn't try this so I don't know if there are any other build errors. Don't use 32bit calibre if you can install the 64bit version.

**Comment by xxyzz** [comment]
Install "Desktop development with C++" from [Visual Studio Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools) and [LLVM](https://github.com/llvm/llvm-project/releases/latest) to build 32bit dependencies. I don't have 32bit Windows but if you guys use 32bit Windows you can give it a try.

**Comment by xxyzz** [comment]
FYI, [spaCy's FAQ](https://github.com/explosion/spaCy/discussions/8226) says "32bit Python is strongly discouraged - use 64bit Python instead."
