### ISSUE TITLE
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

### ISSUE THREAD

**Issue by reiko-3120** [xxyzz/WordDumb#74]
### Describe the bug

error message occur when using WordDumb

### System Information

OS: macOS 12.6
calibre: version 6.5.0

### Error message

```text
calibre, version 6.5.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Final Girls 
Job: "Generating Word Wise and X-Ray for Final Girls" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 100, in do_job
    install_deps(model, book_fmt, notifications)
  File "calibre_plugins.worddumb.deps", line 27, in install_deps
    PY_PATH, PY_VERSION = which_python()
  File "calibre_plugins.worddumb.deps", line 52, in which_python
    r = run_subprocess(
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', 'import platform; print(".".join(platform.python_version_tuple()[:2]))']' returned non-zero exit status 69.
 
Called with args: ((3945, 'MOBI', '/Users/reiko/Library/Mobile Documents/com~apple~CloudDocs/Documents/calibre/Riley Sager/Final Girls (3945)/Final Girls - Riley Sager.mobi', <calibre.ebooks.metadata.book.base.Metadata object at 0x122e88310>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x122e8b9d0>, 'abort': <threading.Event object at 0x122e89300>, 'log': <calibre.utils.logging.GUILog object at 0x122e89a50>} 

You have not agreed to the Xcode license agreements, please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode license agreements.
```

### Reproduce steps

nil

**Comment by xxyzz** [comment]
Please [install Python via Homebrew](https://github.com/xxyzz/WordDumb#how-to-use).
