### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by rxmmah** [xxyzz/WordDumb#76]
### Describe the bug

I really don't know what is happening

### System Information

OS: Mac 13.0 Beta (22A5365d)
Calibre 6.6.1

### Error message

```text
calibre, version 6.6.1 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for A Billion Wicked Thoughts: What the Internet Tells Us About Sexual Relationships 
Job: "Generating Word Wise and X-Ray for A Billion Wicked Thoughts: What the Internet Tells Us About Sexual Relationships" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 142, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/python3', '/Users/kira/Library/Preferences/calibre/plugins/WordDumb.zip', 'BBVKYL4GXH', '/Users/kira/Calibre Library/Ogi Ogas/A Billion Wicked Thoughts_ What the Internet Tells Us About Sexual Relationships (320)/A Billion Wicked Thoughts_ What the Intern - Ogi Ogas.kfx', 'CR!O2N4AXRAH9A33CN28M28E83QE3BJ', '', 'en_core_web_md', 'en', '', 'WordDumb/3.25.1 (https://github.com/xxyzz/WordDumb)', 'cn', '', 'KFX', '1', '/Users/kira/Library/Preferences/calibre/plugins/WordDumb.zip', '', '-l', '-x']' returned non-zero exit status 1.
 
Called with args: ((320, 'KFX', '/Users/kira/Calibre Library/Ogi Ogas/A Billion Wicked Thoughts_ What the Internet Tells Us About Sexual Relationships (320)/A Billion Wicked Thoughts_ What the Intern - Ogi Ogas.kfx', <calibre.ebooks.metadata.book.base.Metadata object at 0x160761a20>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, True) {'notifications': <queue.Queue object at 0x160939ea0>, 'abort': <threading.Event object at 0x160938e50>, 'log': <calibre.utils.logging.GUILog object at 0x160938d60>} 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/kira/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 55, in <module>
  File "/Users/kira/Library/Preferences/calibre/plugins/WordDumb.zip/parse_job.py", line 199, in create_files
  File "/Users/kira/Library/Preferences/calibre/plugins/WordDumb.zip/parse_job.py", line 523, in load_spacy
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/spacy/errors.py", line 2, in <module>
    from .compat import Literal
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/spacy/compat.py", line 38, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/thinc/backends/__init__.py", line 8, in <module>
    from .cupy_ops import CupyOps
  File "/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/thinc/backends/cupy_ops.py", line 4, in <module>
    from .numpy_ops import NumpyOps
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ImportError: dlopen(/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/cymem/cymem.cpython-310-darwin.so, 0x0002): tried: '/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/cymem/cymem.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/cymem/cymem.cpython-310-darwin.so' (no such file), '/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10/cymem/cymem.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

### Reproduce steps

1. select book
2. press on WordDumb

### Screenshots or videos

<img width="603" alt="Screenshot 2022-10-06 at 13 41 02" src="https://user-images.githubusercontent.com/115156210/194303746-40dfbcf5-3d8a-44c0-ac8b-758996671308.png">

**Comment by xxyzz** [comment]
Please delete the `/Users/kira/Library/Preferences/calibre/plugins/worddumb-libs-py3.10` the folder then try again.
