### ISSUE TITLE
Crash while building xray because invalid format of date field in wikimedia data

### ISSUE THREAD

**Issue by jps-e** [xxyzz/WordDumb#83]
### Describe the bug

Crash while building xray because invalid format of date field in wikimedia data.

The URL http://www.wikidata.org/.well-known/genid/7ea35d4504b835fc37b90f06a6e522a

gives "page not found" so I don't know which wikipedia page caused the problem

Maybe inception_text() should catch the error from datetime.fromisoformat()
and return "Bad DateTime format" instead of crashing.

Ugly xray entry, but better than crash.

Or maybe the value of the inception variable needs to be validated before calling inception_text()

### System Information

OS: debian 11 bullseye linux x86_64
calibre version 5.44
python 3.9.2
plugin version 3.22.0

### Error message

```text
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/debug.py", line 315, in main
  File "calibre_plugins.worddumb.__init__", line 70, in cli_main
  File "calibre_plugins.worddumb.parse_job", line 116, in do_job
  File "calibre_plugins.worddumb.parse_job", line 213, in create_files
  File "calibre_plugins.worddumb.x_ray", line 193, in finish
  File "calibre_plugins.worddumb.x_ray", line 80, in insert_descriptions
  File "calibre_plugins.worddumb.mediawiki", line 255, in inception_text
ValueError: Invalid isoformat string: 'http://www.wikidata.org/.well-known/genid/7ea35d4504b835fc37b90f06a6e522a'
```

### Reproduce steps

This happens on a recently published book.

calibre-debug -r WordDumb -- -x BookFileName.azw3

**Comment by xxyzz** [comment]
This error was fixed in v3.23.0. Please delete the Wikidata cache file(`.config/calibre/plugins/worddumb-wikimedia/wikidata.json`) and update to the latest version.
