### ISSUE TITLE
ERROR: Wheel 'en-core-web-trf' located at C:\Users\lemin\AppData\Local\Temp\pip-unpack-s1iyhwc8\en_core_web_trf-3.4.1-py3-none-any.whl is invalid.

### ISSUE THREAD

**Issue by tam-le-6696** [xxyzz/WordDumb#93]
calibre, version 6.9.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Summary of Measure What Matters: How Google, Bono, and the Gates Foundation Rock the World with OKRs by John Doerr: Key Takeaways & Analysis Included 
Job: "Generating Word Wise and X-Ray for Summary of Measure What Matters: How Google, Bono, and the Gates Foundation Rock the World with OKRs by John Doerr: Key Takeaways & Analysis Included" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
  File "calibre_plugins.worddumb.deps", line 54, in install_deps
  File "calibre_plugins.worddumb.deps", line 158, in pip_install
  File "calibre_plugins.worddumb.utils", line 50, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\lemin\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.11', '--no-user', 'https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.4.1/en_core_web_trf-3.4.1-py3-none-any.whl']' returned non-zero exit status 1.
 
Called with args: ((11946, 'AZW3', 'D:\\05-Calibre-Library\\Ninja Reads\\Summary of Measure What Matters_ H (11946)\\Summary of Measure What Matters - Ninja Reads.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x0000023691711690>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x0000023691711570>, 'abort': <threading.Event object at 0x00000236918ECB80>, 'log': <calibre.utils.logging.GUILog object at 0x00000236918EC9A0>} 
ERROR: Wheel 'en-core-web-trf' located at C:\Users\lemin\AppData\Local\Temp\pip-unpack-s1iyhwc8\en_core_web_trf-3.4.1-py3-none-any.whl is invalid.

**Comment by xxyzz** [comment]
Maybe that downloaded package is corrupted. I also notice you're using Python 3.11, which is not supported for the "run spaCy with GPU" feature. Uninstall Python 3.11 and install Python 3.10 instead.

**Comment by tam-le-6696** [comment]
I use Python 3.10 now, and another error pops up :(

calibre, version 6.9.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Procrastination: The Procrastination Cure: How to Stop Being Lazy, Get Things Done & Learn Habits to Change Your Life (Procrastination Cure: Stop Being Lazy and Get Motivated) 
Job: "Generating Word Wise and X-Ray for Procrastination: The Procrastination Cure: How to Stop Being Lazy, Get Things Done & Learn Habits to Change Your Life (Procrastination Cure: Stop Being Lazy and Get Motivated)" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
  File "calibre_plugins.worddumb.deps", line 58, in install_deps
  File "calibre_plugins.worddumb.deps", line 158, in pip_install
  File "calibre_plugins.worddumb.utils", line 50, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\lemin\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.10', '--no-user', 'cupy-wheel==11.3.0']' returned non-zero exit status 1.
 
Called with args: ((11860, 'AZW3', 'D:\\05-Calibre-Library\\Anastasia Ratajkowski\\Procrastination_ The Procrastinati (11860)\\Procrastination_ The Procrastin - Anastasia Ratajkowski.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x000001B222F8C670>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x000001B222F8C910>, 'abort': <threading.Event object at 0x000001B222F8C820>, 'log': <calibre.utils.logging.GUILog object at 0x000001B222F8C400>} 
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [26 lines of output]
  [cupy-wheel] CUDA_PATH is not set.cupy-wheel may not be able to discover NVRTC to probe version
  [cupy-wheel] Trying to detect CUDA version from libraries: ['nvrtc64_112_0.dll', 'nvrtc64_111_0.dll', 'nvrtc64_110_0.dll', 'nvrtc64_102_0.dll']
  [cupy-wheel] Looking for library: nvrtc64_112_0.dll
  [cupy-wheel] Failed to open nvrtc64_112_0.dll: Could not find module 'nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  [cupy-wheel] Looking for library: nvrtc64_111_0.dll
  [cupy-wheel] Failed to open nvrtc64_111_0.dll: Could not find module 'nvrtc64_111_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  [cupy-wheel] Looking for library: nvrtc64_110_0.dll
  [cupy-wheel] Failed to open nvrtc64_110_0.dll: Could not find module 'nvrtc64_110_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  [cupy-wheel] Looking for library: nvrtc64_102_0.dll
  [cupy-wheel] Failed to open nvrtc64_102_0.dll: Could not find module 'nvrtc64_102_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  [cupy-wheel] No more candidate library to find
  [cupy-wheel] ROCm detection unsupported on platform: win32
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\lemin\AppData\Local\Temp\pip-install-c8dtuy_2\cupy-wheel_ce048fd33bf943d2bef208f52f45e127\setup.py", line 295, in <module>
      main()
    File "C:\Users\lemin\AppData\Local\Temp\pip-install-c8dtuy_2\cupy-wheel_ce048fd33bf943d2bef208f52f45e127\setup.py", line 276, in main
      package = infer_best_package()
    File "C:\Users\lemin\AppData\Local\Temp\pip-install-c8dtuy_2\cupy-wheel_ce048fd33bf943d2bef208f52f45e127\setup.py", line 252, in infer_best_package
      raise AutoDetectionFailed(
  __main__.AutoDetectionFailed:
  ============================================================
  Unable to detect NVIDIA CUDA or AMD ROCm installation.
  ============================================================
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tam-le-6696** [comment]
So it works when Create Wordwise, but not with X-Ray

**Comment by xxyzz** [comment]
You can't use the "run spaCy with GPU" feature without CUDA and CUDA supported GPU. I guess you haven't read [the manual](https://github.com/xxyzz/WordDumb#how-to-use).

**Comment by tam-le-6696** [comment]
I read the manual before submitting this issue, but CUDA was something new to me. After you commented, I downloaded the CUDA driver and now everything's fine. The plug-in is working as expected. Thank you!

**Comment by xxyzz** [comment]
I also add a tooltip on the "Run spaCy with GPU" checkbox, it shows a text saying the feature requires CUDA when you hover on it. I should make it more obvious.
