### ISSUE TITLE
Bug when trying to run plugin

### ISSUE THREAD

**Issue by UKFan643** [xxyzz/WordDumb#96]
calibre, version 6.10.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Red War 
Job: "Generating Word Wise and X-Ray for Red War" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 167, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 59, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '/Users/mini/Library/Preferences/calibre/plugins/WordDumb.zip', 'B07B3WJ9X7', '/Users/mini/Calibre Library/Vince Flynn/Red War (145)/Red War - Vince Flynn.azw3', 'Red_War', '1b1ca15b', 'en_core_web_lg', 'en', 'en', 'utf-8', 'WordDumb/3.28.0 (https://github.com/xxyzz/WordDumb)', 'cn', '', 'AZW3', '1', '/Users/mini/Library/Preferences/calibre/plugins/WordDumb.zip', '', '-l', '-x', '-s']' returned non-zero exit status 1.
 
Called with args: ((145, 'AZW3', '/Users/mini/Calibre Library/Vince Flynn/Red War (145)/Red War - Vince Flynn.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x11d2cf8e0>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x11d2cddb0>, 'abort': <threading.Event object at 0x11d2cea40>, 'log': <calibre.utils.logging.GUILog object at 0x11d2cef80>} 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mini/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/mini/Library/Preferences/calibre/plugins/WordDumb.zip/dump_kindle_lemmas.py", line 13, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by xxyzz** [comment]
[Only Python 3.10 or newer is supported](https://github.com/xxyzz/WordDumb#how-to-use), please update your Python package.

**Comment by UKFan643** [comment]
calibre, version 6.10.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Red War 
Job: "Generating Word Wise and X-Ray for Red War" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
    install_deps(model, notifications)
  File "calibre_plugins.worddumb.deps", line 71, in install_deps
    pip_install("lxml", dep_versions["lxml"], notif=notif)
  File "calibre_plugins.worddumb.deps", line 158, in pip_install
    run_subprocess(args)
  File "calibre_plugins.worddumb.utils", line 59, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', '/Users/mini/Library/Preferences/calibre/plugins/worddumb-libs-py3.10', '--no-user', 'lxml==4.9.1']' returned non-zero exit status 1.
 
Called with args: ((145, 'AZW3', '/Users/mini/Calibre Library/Vince Flynn/Red War (145)/Red War - Vince Flynn.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x127430700>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), True, True) {'notifications': <queue.Queue object at 0x1274333a0>, 'abort': <threading.Event object at 0x1274307f0>, 'log': <calibre.utils.logging.GUILog object at 0x12740b520>} 
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against libxml2 2.9.13 and libxslt 1.1.35
      Building against libxml2/libxslt in the following directory: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-x86_64-cpython-310
      creating build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/sax.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/rng
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-13-x86_64-cpython-310
      creating build/temp.macosx-13-x86_64-cpython-310/src
      creating build/temp.macosx-13-x86_64-cpython-310/src/lxml
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DCYTHON_CLINE_IN_TRACEBACK=0 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Isrc -Isrc/lxml/includes -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/lxml/etree.c -o build/temp.macosx-13-x86_64-cpython-310/src/lxml/etree.o -w -flat_namespace
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13'
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/21
      creating var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn
      creating var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn/T
      cc -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/include/libxml2 -c /var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn/T/xmlXPathInitg7gfjs7e.c -o var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn/T/xmlXPathInitg7gfjs7e.o
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13'
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  error: subprocess-exited-with-error
  
  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against libxml2 2.9.13 and libxslt 1.1.35
      Building against libxml2/libxslt in the following directory: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-x86_64-cpython-310
      creating build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/sax.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-13-x86_64-cpython-310/lxml
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/html
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-13-x86_64-cpython-310/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-13-x86_64-cpython-310/lxml/includes
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/rng
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-13-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-13-x86_64-cpython-310
      creating build/temp.macosx-13-x86_64-cpython-310/src
      creating build/temp.macosx-13-x86_64-cpython-310/src/lxml
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DCYTHON_CLINE_IN_TRACEBACK=0 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Isrc -Isrc/lxml/includes -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/lxml/etree.c -o build/temp.macosx-13-x86_64-cpython-310/src/lxml/etree.o -w -flat_namespace
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13'
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      cc -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/include/libxml2 -c /var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn/T/xmlXPathInitl5fuxj6g.c -o var/folders/21/qrm3jf8128g3c4zdn09t7rdr0000gn/T/xmlXPathInitl5fuxj6g.o
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13'
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by UKFan643** [comment]
Didn't want to open a whole new issue. Updated to 3.10 and now I'm getting this error.

**Comment by xxyzz** [comment]
lxml 4.9.1 doesn't have wheel file for Python 3.10 on macOS, so pip tries to build that package but failed. I update the package in this commit: https://github.com/xxyzz/WordDumb/commit/739fe9c9fc7571e06d9c28f6648c608defb40db4 and it should fix this error.

**Comment by UKFan643** [comment]
> lxml 4.9.1 doesn't have wheel file for Python 3.10 on macOS, so pip tries to build that package but failed. I update the package in this commit: [739fe9c](https://github.com/xxyzz/WordDumb/commit/739fe9c9fc7571e06d9c28f6648c608defb40db4) and it should fix this error.

Forgive me, but I have no idea what this means. Is there something I need to do to update or is it just going to take a plugin update? Sorry.

**Comment by xxyzz** [comment]
You can download and install the test plugin from [GitHub Actions Artifacts](https://github.com/xxyzz/WordDumb/actions/workflows/tests.yml), the latest job is here: https://github.com/xxyzz/WordDumb/actions/runs/3727986103

**Comment by xxyzz** [comment]
You can use the "Load plugin from file" button in the calibre plugins window to load the test plugin zip file. Newly installed plugin requires restart calibre to take effect.

**Comment by UKFan643** [comment]
I just can't figure this out. I'm downloading the linked file, though it's a folder. I tried compressing it and then loading it from file that way, but then I get this error. I know it has to be a .zip to add as a plugin, but compressing the file didn't work. 

> calibre, version 6.10.0
> ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/mini/Downloads/worddumb-v3/worddumb-v3.zip' is invalid. It does not contain a top-level __init__.py file
> 
> calibre 6.10  embedded-python: True
> macOS-13.0-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  2 22:39:24 PDT 2022; root:xnu-8792.41.7~13/RELEASE_X86_64')
> Python 3.10.1
> OSX: ('13.0', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 50, 0) && Extract ISBN (1, 6, 0) && Goodreads (1, 7, 1) && Goodreads Sync (1, 16, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0) && Quality Check (1, 13, 3)
> Traceback (most recent call last):
>   File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
>   File "calibre/customize/ui.py", line 479, in add_plugin
>   File "calibre/customize/ui.py", line 64, in load_plugin
>   File "calibre/customize/zipplugin.py", line 298, in load
>   File "calibre/customize/zipplugin.py", line 393, in _locate_code
> calibre.customize.InvalidPlugin: The plugin in '/Users/mini/Downloads/worddumb-v3/worddumb-v3.zip' is invalid. It does not contain a top-level __init__.py file
>

**Comment by xxyzz** [comment]
macOS deletes the `__init__.py` file when compress a folder in Finder, please re-download the zip file from GitHub.
