### ISSUE TITLE
Generating X-Ray or Word Wise failed

### ISSUE THREAD

**Issue by LorandMarton** [xxyzz/WordDumb#97]
### Checkboxes

- [X] I have read the [README](https://github.com/xxyzz/WordDumb#how-to-use) file.
- [X] I have not found similar issue or disscussion at GitHub.

### Describe the bug

Generating X-ray or word-wise does not work, it gives an error.

### System Information

windows 10
Calibre 6.10.0 64 bit
WordDumb 3.28.1
python  3.11.1 64 bit

### Error message

```text
calibre, version 6.10.0 (win32, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating X-Ray for -------- 
Job: "Generating X-Ray for -------" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 119, in do_job
  File "calibre_plugins.worddumb.deps", line 54, in install_deps
  File "calibre_plugins.worddumb.deps", line 158, in pip_install
  File "calibre_plugins.worddumb.utils", line 50, in run_subprocess
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['py', '-m', 'pip', '--disable-pip-version-check', 'install', '-U', '-t', 'C:\\Users\\-----\\AppData\\Roaming\\calibre\\plugins\\worddumb-libs-py3.11', '--no-user', 'https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.4.1/en_core_web_trf-3.4.1-py3-none-any.whl']' returned non-zero exit status 1.
 
Called with args: ((92, 'AZW3', 'C:\\Users\\-------\\Books\\Calibre Library\\------, (92)\\--------.azw3', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000246888D8130>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English', 'gloss': True, 'has_trf': True}), False, True) {'notifications': <queue.Queue object at 0x00000246888D8E50>, 'abort': <threading.Event object at 0x0000024688962440>, 'log': <calibre.utils.logging.GUILog object at 0x0000024688962500>} 
ERROR: Cannot install en-core-web-trf because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

### Reproduce steps

1. Click the icon to generate X-Ray or Word Wise or both
2. Get the error

**Comment by xxyzz** [comment]
PyTorch only supports Python 3.11 for Linux, uninstall Python 3.11 then install Python 3.10. It's written in the README file.
